In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('../data/flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
1104,2 BHK Flat in Sector 82 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Vatika The Seven Lamps3.8 ★,94.25 Lac,"₹ 6,567/sq.ft.",Super Built up area 1435(133.32 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 82 Gurgaon, Gurgaon, Haryana",12nd of 16 Floors,East,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","Brokers excuse, 2bhk, study, 1435 sq. Ft., nor...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of...",J69790804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,2 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Ramprastha The Edge Towers3.5 ★,71 Lac,"₹ 5,420/sq.ft.",Super Built up area 1310(121.7 sq.m.)Built Up ...,2 Bedrooms,2 Bathrooms,3 Balconies,Others,"Gurgaon, Sector 37D Gurgaon, Gurgaon, Haryana",10th of 22 Floors,South-East,0 to 1 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...",Residential apartment for sell.Located in sect...,[],"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4 out of 5', 'Amenities4 out of 5'...",W38206361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
577,2 BHK Flat in Sector 107 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global Solera3.7 ★,27.75 Lac,"₹ 5,674/sq.ft.",Carpet area: 489 (45.43 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 107 Gurgaon, Gurgaon, Haryana",6th of 14 Floors,West,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",This lovely 2 bhk apartment/flat in sector 107...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou...",E69217168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1421,2 BHK Flat in Sector 37C Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apex Our Homes,35 Lac,"₹ 3,783/sq.ft.",Super Built up area 925(85.94 sq.m.)Built Up a...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"753, Sector 37C Gurgaon, Gurgaon, Haryana",7th of 11 Floors,East,1 to 5 Year Old,"['Elvedor Mall', 'MDS Public School', 'K.D. Ho...",Check out this 2 bhk apartment for sale in ape...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle4 out of 5...",P70095968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1915,2 BHK Flat in Sector 91 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,TARC Maceo3.8 ★,90 Lac,"₹ 6,870/sq.ft.",Super Built up area 1310(121.7 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 91 Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,East,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",Fully furnished east facing flat.,"['1 Water Purifier', '3 Fan', '1 Fridge', '1 D...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of...",A70182296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print(df.columns)

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'property_id', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28'],
      dtype='object')

In [5]:
df = df.drop(columns=['Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28'])
print(df.columns)

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='object')

In [6]:
# shape
df.shape

(3017, 20)

In [7]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [8]:
# check for duplicates
df.duplicated().sum()

np.int64(0)

In [9]:
# check for missing values
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [10]:
# Columns to drop -> property_name, link, property_id
df.drop(columns=['link','property_id'], inplace=True)

In [11]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [12]:
# rename columns
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [13]:
# society
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Vatika Gurgaon 213.7 ★                               24
DLF New Town Heights 13.9 ★                          24
Bestech Park View Residency3.9 ★                     23
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
ATS Triumph3.9 ★                                     22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Ambience Creacions                                   18
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Mapsko Mount Ville4.1 ★                              18
Supertech Araville                                   18
CHD Avenue 713.6 ★                                   18
Sobha City                                           18
M3M Golfestate4.4 ★                                  17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
Godrej Summit3.7 ★                                   17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Bestech Park View Grand Spa4.3 ★                     16
M3M Merlin3.7 ★                                      16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
Godrej Oasis3.9 ★                                    15
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
DLF The Primus3.9 ★                                  14
Orchid Petals4.1 ★                                   14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Ireo Victory Valley4.1 ★                             14
Indiabulls Enigma                                    14
Corona Optus3.9 ★                                    14
Imperia The Esfera                                   14
MVN Athens3.7 ★                                      14
Ireo The Corridors                                   13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
M3M Soulitude                                        11
DLF The Skycourt4.2 ★                                11
Godrej Aria3.8 ★                                     11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Breez Global Hill View                               11
Adani M2K Oyster Grande3.9 ★                         11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
ATS Kocoon                                           10
Ramprastha The Edge Towers3.5 ★                      10
Signature Global Synera3.4 ★                         10
DLF New Town Heights 24.0 ★                          10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Zara Aavaas                                          10
Pyramid Urban Homes 2                                10
Godrej Air                                           10
Pivotal Devaan                                       10
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Pareena Mi Casa                                       9
Microtek Greenburg3.8 ★                               9
ILD Greens4.1 ★                                       9
Vatika City4.1 ★                                      9
Tulip Ivory3.5 ★                                      8
GLS Avenue 51                                         8
ss                                                    8
Bestech Altura                                        8
AVL 36 Gurgaon3.7 ★                                   8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Emaar Digihomes                                       8
M3M Capital                                           8
Birla Navya                                           8
Assotech Blith                                        8
Vatika Lifestyle Homes3.8 ★                           8
M3M Skycity                                           8
Signature Andour Heights3.8 ★                         7
Emaar Imperial Gardens3.8 ★                           7
Signature Global Orchard Avenue3.6 ★                  7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
Vipul Lavanya3.9 ★                                    7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Sare Green ParC Phase 3                               7
Ansal Housing Highland Park                           7
Orris Carnation Residency3.7 ★                        7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
DLF Regency Park 13.6 ★                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Mapsko Royale Ville3.7 ★                              6
Sidhartha NCR One Phase 14.2 ★                        6
Greenopolis                                           6
Hero Homes                                            6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Pyramid Urban                                         6
Shapoorji Pallonji Joyville Gurugram                  6
Supertech Hues                                        6
Ashiana Mulberry                                      6
BPTP Astaire Gardens3.7 ★                             6
Pioneer Araya3.8 ★                                    6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
M3M Sierra 68                                         6
Kiran Residency                                       6
Ireo Uptown4.1 ★                                      5
Silverglades The Melia                                5
Signature Global Grand IVA3.9 ★                       5
Conscient Elevate                                     5
Godrej Habitat                                        5
Essel Towers                                          5
Vatika Sovereign Park                                 5
ATS Marigold                                          5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
Krisumi Waterfall Residences                          5
Central Park Flower Valley Aqua Front Towers          5
Ashiana Anmol3.5 ★                                    5
Green Court3.7 ★                                      5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Emaar MGF Emerald Estate3.8 ★                         5
Pioneer Park3.8 ★                                     5
Signature Global City 92                              5
Signature Global the Millennia                        5
DLF Regency Park 24.0 ★                               5
Central Park Resorts4.4 ★                             5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Signature Global City 81                              5
Apna Enclave                                          5
Unitech Vistas                                        4
Global Hill View                                      4
Railway Officers RPF Society                          4
Corona Gracieux                                       4
ILD Grand                                             4
Sare Petioles                                         4
Raheja Navodaya3.6 ★                                  4
Ramprastha Primera                                    4
Unitech Fresco3.8 ★                                   4
Signature The Serenas                                 4
Godrej Frontier3.7 ★                                  4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
Ramprastha Skyz                                       4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
SS The Coralwood3.4 ★                                 4
Lotus Homz4.0 ★                                       4
DLF The Skycourt                                      4
Orris Aster Court                                     4
Godrej Icon                                           4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Spaze Privvy The Address3.9 ★                         3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Ambience Lagoon3.9 ★                                  3
Unitech Heritage City                                 3
The Roselia 2                                         3
Valley View Estate                                    3
Sare Green Parc                                       3
Vatika Independent Floors3.8 ★                        3
Kendriya Vihar4.1 ★                                   3
Piedmont Taksila heights3.6 ★                         3
DLF The Grove                                         3
Tulip Petals3.6 ★                                     3
Shri Ram Apartments                                   3
Unitech Uniworld Gardens3.8 ★                         3
Tulip White3.5 ★                                      3
Smriti Apartment                                      3
Sapphire Eighty Three                                 3
DLF Royalton Tower                                    3
DLF Carlton Estate4.0 ★                               3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Belvedere Towers3.8 ★                             3
Satya Element One                                     3
AIPL Club Residences                                  3
Vatika Xpressions                                     3
Raheja Revanta                                        3
My Home                                               3
Brisk Lumbini Terrace Homes                           3
Deepak Minda                                          3
Maxworth City Residences                              3
Apex Our Homes                                        3
Shri Banke Bihari Society3.8 ★                        3
AFNHB Jalvayu Vihar3.7 ★                              3
Spaze Privy AT43.9 ★                                  3
ATS Kocoon4.2 ★                                       3
Dhoot Time Residency4.0 ★                             3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Sunischit Apartments                                  3
Bestech Park View City 23.9 ★                         3
Pyramid Elite                                         3
Suncity Platinum Towers                               3
Mahindra Aura4.2 ★                                    3
Shree Arihant Apartment                               3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Pivotal Riddhi Siddhi                                 3
Adani Aangan Arcade                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Tulip Purple                                          3
Chintels Paradiso3.9 ★                                3
Essel Tower                                           3
Unitech Sunbreeze                                     3
Raheja Atharva3.6 ★                                   3
Krrish Florence Estate                                3
Sidhartha NCR Greens4.3 ★                             3
Paras Quartier                                        3
Spaze Privy3.9 ★                                      3
Unitech The Residences3.7 ★                           3
Tulip Lemon3.9 ★                                      3
Puri Diplomatic Greens3.9 ★                           3
Conscient Habitat3.6 ★                                3
Today Callidora                                       2
Landmark The Residency                                2
Ramprastha The Atrium3.4 ★                            2
Samaspurkunj                                          2
Mahindra Luminare4.0 ★                                2
Maruti Vihar                                          2
Vipul World Floors                                    2
Unitech Uniworld Gardens 23.4 ★                       2
Apartment                                             2
Lavanya Apartments                                    2
Park Royal Apartment                                  2
Vasant Appartments                                    2
Surendra Avenue 69                                    2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Mapsko Paradise3.9 ★                                  2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Sidhivinayak Apartments                               2
Bhagwati Sadan                                        2
Ambience Caitriona                                    2
Breeze Global Heights                                 2
Silverglades Hightown Residences                      2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Milan CGHS 9                                          2
Element One Service                                   2
om appartments                                        2
Ansal Heights3.2 ★                                    2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
M3M Sky Lofts                                         2
Supertech Hilltown                                    2
Bestech Spa Signature                                 2
M3M Latitude                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
Raheja Vanya                                          2
Housing Board Colony                                  2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
Tulip Orange3.9 ★                                     2
Central Park 2 Bellevue                               2
M3M Urbana                                            2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Ashiana Anmol                                         2
Godrej Nature Plus Serenity                           2
The Close South3.9 ★                                  2
Ganga Apartment                                       2
Suncity Heights3.7 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Oriental Valley CHS                                   2
Aqua Front Towers                                     2
Sahara Grace                                          2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
Pioneer Urban Presidia                                2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Emaar MGF The Enclave                                 2
Ramprastha City                                       2
Vipul Belmonte3.9 ★                                   2
BPTP Amstoria3.8 ★                                    2
The Penthouses at the Hibiscus                        2
M3M Ikonic                                            2
Vatika Emilia Floors3.7 ★                             2
Ardee City3.8 ★                                       2
Tulip Violet                                          2
Tulip Leaf                                            2
Viridian The Plaza 106                                2
Signature Global The Millennia 3                      2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
Bestech Park View Sanskruti4.1 ★                      2
Professors Enclave CGHS                               2
DLF The Icon3.7 ★                                     2
SS Hibiscus                                           2
BPTP Mansions Park Prime                              2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
Puri The Aravallis                                    2
Paras Irene3.7 ★                                      2
BPTP Freedom Park Life4.0 ★                           2
Tulsiani Easy in Homes                                2
The Center Court                                      1
Uphaar Residency 2                                    1
Wings Apartment                                       1
Sidhartha NCR One Phase 24.1 ★                        1
Bestech Park View Ananda                              1

Comment: Need to clean text of society column. need to remove ratings

In [14]:
df['society'].value_counts().shape

(638,)

Comment: Total 638 unique values for society. But it may contain duplicates since smallcase e nei, rating o ache

In [15]:
# Removing unnecessary text from society column
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [16]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [17]:
df['society'].value_counts().shape

(604,)

Comment: Now total 604 unique values for society.

In [18]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
emaar mgf emerald floors premier                 32
smart world gems                                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
signature global solera                          28
la vida by tata housing                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
vatika gurgaon                                   24
experion the heartsong                           24
eldeco accolade                                  24
bestech park view residency                      23
m3m heights                                      22
emaar palm gardens                               22
ats triumph                                      22
tata primanti                                    22
rof ananda                                       21
sare crescent parc                               21
godrej                                           21
experion windchants                              20
antriksh heights                                 19
sare homes                                       19
mapsko mount ville                               18
indiabulls centrum park                          18
ambience creacions                               18
m3m golfestate                                   18
chd avenue                                       18
ats tourmaline                                   18
m3m skywalk                                      18
hcbs sports ville                                18
sobha city                                       18
supertech araville                               18
godrej summit                                    17
pareena coban residences                         17
conscient heritage max                           17
gls arawali homes                                17
m3m merlin                                       16
bestech park view grand spa                      16
umang monsoon breeze                             15
ramsons kshitij                                  15
godrej oasis                                     15
dlf the skycourt                                 15
ansal heights 86                                 15
emaar mgf the palm drive                         15
corona optus                                     14
ireo victory valley                              14
the close north                                  14
imperia the esfera                               14
vatika the seven lamps                           14
dlf the primus                                   14
ireo skyon                                       14
bestech park view ananda                         14
orchid petals                                    14
mvn athens                                       14
umang winter hills                               14
indiabulls enigma                                14
central park flower valley                       13
ireo the corridors                               13
puri diplomatic greens                           13
puri emerald bay                                 13
ats kocoon                                       13
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
breez global hill view                           11
tarc maceo                                       11
sbtl caladium                                    11
adani m2k oyster grande                          11
dlf regency park                                 11
m3m soulitude                                    11
raheja vedaanta                                  11
breez global heights                             11
godrej aria                                      11
emaar mgf palm hills                             10
pyramid urban homes 2                            10
ild greens                                       10
pivotal devaan                                   10
godrej air                                       10
ramprastha the edge towers                       10
zara aavaas                                      10
signature global synera                          10
capital residences 360                           10
aipl the peaceful homes                           9
parsvnath green ville                             9
vatika city                                       9
microtek greenburg                                9
pareena mi casa                                   9
bestech park view city                            9
avl 36 gurgaon                                    8
m3m capital                                       8
the lions cghs                                    8
birla navya                                       8
bestech altura                                    8
orris aster court premier                         8
emaar digihomes                                   8
ss                                                8
assotech blith                                    8
gls avenue 51                                     8
tulip ivory                                       8
vatika lifestyle homes                            8
m3m skycity                                       8
ansal housing highland park                       7
signature global orchard avenue                   7
ireo the grand arch                               7
sidhartha ncr one phase                           7
signature andour heights                          7
aipl zen residences                               7
orris carnation residency                         7
mapsko casa bella                                 7
sare crescent parc royal greens phase 1           7
signature global city                             7
emaar imperial gardens                            7
sare green parc phase 3                           7
vipul lavanya                                     7
trisara our homes 3                               7
ashiana anmol                                     7
bptp astaire gardens                              6
pyramid urban                                     6
supertech hues                                    6
signature the roselia                             6
green court                                       6
hero homes                                        6
parsvnath exotica                                 6
bestech park view spa next                        6
greenopolis                                       6
kiran residency                                   6
pioneer araya                                     6
m3m sierra 68                                     6
ashiana mulberry                                  6
mapsko royale ville                               6
suncity vatsal valley                             6
signature global park 4                           6
hsiidc sidco aravali                              6
signature global city 63a                         6
central park flower valley aqua front towers      5
signature global grand iva                        5
godrej habitat                                    5
signature global city 81                          5
unitech fresco                                    5
vatika sovereign park                             5
conscient elevate                                 5
ats marigold                                      5
tulip monsella                                    5
adani brahma samsara vilasa                       5
signature global city 37d ph 2                    5
pareena laxmi apartments                          5
satya the hermitage                               5
signature global the millennia                    5
m3m the marina                                    5
pioneer park                                      5
krisumi waterfall residences                      5
emaar mgf emerald estate                          5
central park resorts                              5
silverglades the melia                            5
signature global city 92                          5
unitech uniworld gardens                          5
essel towers                                      5
dlf park place                                    5
ireo uptown                                       5
vatika city homes                                 5
apna enclave                                      5
ild grand                                         4
raheja navodaya                                   4
ramprastha skyz                                   4
unitech vistas                                    4
signature the serenas                             4
railway officers rpf society                      4
afnhb jalvayu vihar                               4
lotus homz                                        4
dlf the arbour                                    4
hsiidc sidco shivalik apartments                  4
ramprastha primera                                4
godrej icon                                       4
krrish provence estate                            4
global hill view                                  4
kendriya vihar                                    4
essel tower                                       4
sare petioles                                     4
corona gracieux                                   4
emaar palm heights                                4
ss the coralwood                                  4
prime habitat                                     4
orris aster court                                 4
godrej frontier                                   4
tata gurgaon gateway                              4
unitech sunbreeze                                 3
brisk lumbini terrace homes                       3
smriti apartment                                  3
dlf carlton estate                                3
pivotal riddhi siddhi                             3
sidhartha ncr one                                 3
raheja sampada                                    3
pyramid elite                                     3
signature global solera 2                         3
my home                                           3
tulip petals                                      3
sare green parc 2                                 3
dlf express greens                                3
spaze privvy the address                          3
shri ram apartments                               3
spaze privy                                       3
raheja revanta                                    3
tulip lemon                                       3
conscient habitat                                 3
guru gram haryana cghs                            3
dhoot time residency                              3
sunischit apartments                              3
vatika xpressions                                 3
mahindra aura                                     3
bhagwati sadan                                    3
valley view estate                                3
siddhartha apartment                              3
dlf royalton tower                                3
the roselia 2                                     3
satya element one                                 3
apex our homes                                    3
spaze privy at                                    3
suncity platinum towers                           3
vatika independent floors                         3
shri banke bihari society                         3
whiteland blissville                              3
aipl club residences                              3
maxworth city residences                          3
dlf belvedere towers                              3
paras quartier                                    3
unitech the residences                            3
ambience lagoon                                   3
raheja atharva                                    3
krrish florence estate                            3
piedmont taksila heights                          3
sidhartha ncr greens                              3
deepak minda                                      3
unitech heritage city                             3
sapphire eighty three                             3
sukhshanti apartment                              3
tulip white                                       3
tulip purple                                      3
chintels paradiso                                 3
adani aangan arcade                               3
sare green parc                                   3
shree arihant apartment                           3
ss almeria                                        3
dlf the grove                                     3
puri the aravallis                                2
aqua front towers                                 2
today callidora                                   2
park royal apartment                              2
sahara grace                                      2
housing board colony                              2
bptp pedestal                                     2
mrg world ultimus                                 2
mapsko paradise                                   2
professors enclave cghs                           2
breeze global heights                             2
dlf city                                          2
ramprastha the atrium                             2
shapoorji pallonji joyville                       2
dlf the icon                                      2
element one service                               2
silverglades hightown residences                  2
nbcc heights                                      2
suncity heights                                   2
ambience caitriona                                2
surendra avenue 69                                2
jammu and kashmir bank employees cghs             2
sidhivinayak apartments                           2
oriental valley chs                               2
emaar mgf emerald floors                          2
maruti vihar                                      2
raheja atlantis                                   2
central park 2 bellevue                           2
tulip orange                                      2
adani aangan galleria                             2
milan cghs 9                                      2
ansal api celebrity suites                        2
cghs airport apartment                            2
ansal heights                                     2
m3m urbana                                        2
vatika inxt floors                                2
palam vihar society                               2
m3m latitude                                      2
pioneer urban presidia                            2
elan the presidential                             2
lagoon apartment                                  2
rof aalayas                                       2
signature global the millennia 3                  2
m3m sky lofts                                     2
vasant appartments                                2
shree shyam residency                             2
shyam apartment                                   2
ansal api esencia                                 2
mahindra luminare                                 2
bptp freedom park life                            2
the close south                                   2
landmark the residency                            2
awho shanti vihar                                 2
raheja vanya                                      2
godrej nature plus serenity                       2
suncity avenue 76                                 2
supertech hill town                               2
vipul world floors                                2
viridian the plaza 106                            2
ss hibiscus                                       2
the penthouses at the hibiscus                    2
bestech spa signature                             2
emaar mgf palm studios                            2
vatika emilia floors                              2
tulip leaf                                        2
ardee city                                        2
residency grand                                   2
ss residency                                      2
om appartments                                    2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
supertech hilltown                                2
ganga apartment                                   2
apartment                                         2
lavanya apartments                                2
samaspurkunj                                      2
ramprastha city                                   2
orchid island                                     2
dlf the crest                                     2
green campus chs                                  2
suncity avenue                                    2
dlf the belaire                                   2
paras irene                                       2
bptp amstoria                                     2
m3m ikonic                                        2
vipul belmonte                                    2
emaar mgf the enclave                             2
bptp mansions park prime                          2
tulsiani easy in homes                            2
spire woods now ananda by alpha corp              1
maa bhagwati residency                            1
parkwood westend                                  1
signature global infinity mall                    1
the cocoon                                        1
divya apartments                                  1
ansals highland park                              1
ild grand centra                                  1
sobha smriti apartments                           1
conscient one                                     1
emaar palm premier                                1
lig flat                                          1
aditya apartment                                  1
ramprasta awho                                    1
maple heights                                     1
ikon tower baani city centre                      1
mittal cosmos executive apartments                1
ansal harmony homes                               1
shree balaji appartment                           1
ashok vihar phase 2                               1
central park flower valley cerise floors          1
lord krishna                                      1
unitech harmony                                   1
.                                                 1
emaar mgf palm terraces select                    1
hector trimurti heights                           1
unitech uniworld city                             1
bhawna cghs                                       1
ompee k s residency                               1
apex builders                                     1
central park resort belgravia residences          1
the serenas                                       1
the new people apartments                         1
chanderlok society                                1
ansal estella                                     1
laxmi apartment sector 99a gurgaon                1
sanskriti apartments                              1
millenia                                          1
emaar emerald hills                               1
ansal maple heights                               1
the nav manesar apartment                         1
signature global orchard avenue 2                 1

In [19]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [20]:
# price
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.9 Crore           40
1.55 Crore          40
75 Lac              38
1.65 Crore          38
1.7 Crore           37
1.8 Crore           37
80 Lac              36
2.2 Crore           34
1.15 Crore          33
50 Lac              33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
60 Lac              29
40 Lac              29
2.5 Crore           29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.3 Crore           18
2.4 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
82 Lac              13
3.25 Crore          13
92 Lac              13
38 Lac              13
78 Lac              13
2.7 Crore           13
1.32 Crore          13
5 Crore             12
42 Lac              12
1.95 Crore          12
1.42 Crore          12
2.8 Crore           12
25 Lac              11
88 Lac              11
Price on Request    11
32 Lac              11
1.08 Crore          11
1.28 Crore          10
26 Lac              10
87 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
28 Lac              10
2.85 Crore           9
1.72 Crore           9
1.68 Crore           9
3.45 Crore           9
4 Crore              9
2.05 Crore           9
99 Lac               9
36 Lac               9
22 Lac               9
48 Lac               8
20 Lac               8
2.75 Crore           8
4.25 Crore           8
86 Lac               8
27 Lac               8
1.26 Crore           8
6.5 Crore            8
1.54 Crore           8
1.18 Crore           8
1.76 Crore           8
3.2 Crore            8
6 Crore              8
98 Lac               8
56 Lac               8
39 Lac               7
2.9 Crore            7
72 Lac               7
97 Lac               7
1.27 Crore           7
46 Lac               7
1.36 Crore           7
3.7 Crore            7
1.99 Crore           7
1.19 Crore           7
1.02 Crore           7
1.29 Crore           7
3.3 Crore            7
79 Lac               7
1.16 Crore           6
2.95 Crore           6
1.14 Crore           6
96 Lac               6
3.05 Crore           6
1.51 Crore           6
1.34 Crore           6
1.13 Crore           6
71.5 Lac             6
1.07 Crore           6
5.5 Crore            6
1.59 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.01 Crore           6
43 Lac               6
37 Lac               6
3.35 Crore           6
4.1 Crore            6
1.49 Crore           6
1.39 Crore           6
3.65 Crore           6
3.9 Crore            6
1.24 Crore           5
6.75 Crore           5
1.33 Crore           5
29 Lac               5
1.47 Crore           5
2.22 Crore           5
1.69 Crore           5
64 Lac               5
1.91 Crore           5
4.5 Crore            5
3.75 Crore           5
1.43 Crore           5
1.82 Crore           5
1.83 Crore           5
49 Lac               5
1.92 Crore           5
66 Lac               5
24 Lac               5
1.93 Crore           5
68 Lac               5
1.62 Crore           5
1.79 Crore           5
2.29 Crore           5
93 Lac               5
2.78 Crore           5
2.12 Crore           5
1.44 Crore           5
1.17 Crore           5
1.23 Crore           4
58 Lac               4
41.5 Lac             4
1.22 Crore           4
1.48 Crore           4
1.71 Crore           4
6.15 Crore           4
7 Crore              4
4.85 Crore           4
4.3 Crore            4
1.66 Crore           4
31 Lac               4
3.1 Crore            4
67 Lac               4
36.5 Lac             4
33 Lac               4
73 Lac               4
89 Lac               4
28.5 Lac             4
1.58 Crore           4
5.9 Crore            4
5.6 Crore            4
2.09 Crore           4
1.31 Crore           4
74 Lac               4
1.37 Crore           4
1.52 Crore           4
5.25 Crore           4
1.73 Crore           4
62 Lac               4
3.6 Crore            4
1.77 Crore           4
1.64 Crore           4
3.95 Crore           4
4.75 Crore           3
3.8 Crore            3
1.04 Crore           3
2.28 Crore           3
2.03 Crore           3
1.09 Crore           3
2.08 Crore           3
1.67 Crore           3
1.57 Crore           3
2.36 Crore           3
91 Lac               3
4.8 Crore            3
2.51 Crore           3
3.15 Crore           3
2.24 Crore           3
52 Lac               3
69 Lac               3
83 Lac               3
1.21 Crore           3
2.01 Crore           3
94 Lac               3
72.5 Lac             3
5.8 Crore            3
1.63 Crore           3
3.85 Crore           3
1.41 Crore           3
84 Lac               3
34 Lac               3
2.33 Crore           3
51 Lac               3
2.79 Crore           3
1.88 Crore           3
64.5 Lac             3
3.49 Crore           3
4.2 Crore            3
47 Lac               3
56.2 Lac             2
3.55 Crore           2
7.5 Crore            2
27.1 Lac             2
11 Crore             2
4.55 Crore           2
2.87 Crore           2
2.26 Crore           2
87.5 Lac             2
52.56 Lac            2
2.14 Crore           2
2.99 Crore           2
1.56 Crore           2
2.58 Crore           2
2.57 Crore           2
5.2 Crore            2
5.7 Crore            2
2.13 Crore           2
1.46 Crore           2
8 Crore              2
8.5 Crore            2
2.17 Crore           2
59 Lac               2
3.29 Crore           2
71 Lac               2
6.2 Crore            2
2.23 Crore           2
53.5 Lac             2
2.52 Crore           2
4.49 Crore           2
2.04 Crore           2
27.75 Lac            2
4.7 Crore            2
88.5 Lac             2
2.41 Crore           2
2.02 Crore           2
4.26 Crore           2
3.32 Crore           2
4.6 Crore            2
3.21 Crore           2
25.5 Lac             2
14 Crore             2
4.45 Crore           2
98.5 Lac             2
1.87 Crore           2
2.91 Crore           2
53 Lac               2
31.5 Lac             2
77.5 Lac             2
41 Lac               2
3.19 Crore           1
5.31 Crore           1
4.95 Crore           1
4.02 Crore           1
97.04 Lac            1
37.5 Lac             1
68.85 Lac            1
98.88 Lac            1
2.69 Crore           1
2.54 Crore           1
54.8 Lac             1
3.98 Crore           1
94.5 Lac             1
2.44 Crore           1
82.5 Lac             1
61 Lac               1
29.8 Lac             1
6.02 Crore           1
7.9 Crore            1
3.23 Crore           1
15 Crore             1
7.8 Crore            1
1.97 Crore           1
39.5 Lac             1
11.25 Crore          1
7.15 Crore           1
2.82 Crore           1
54.99 Lac            1
6.44 Crore           1
1.11 Crore           1
8.25 Crore           1
31.75 Lac            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
55.5 Lac             1
5.4 Crore            1
3.39 Crore           1
95.75 Lac            1
3.46 Crore           1
3.63 Crore           1
4.67 Crore           1
2.37 Crore           1
4.4 Crore            1
66.99 Lac            1
6.3 Crore            1
23 Lac               1
5.49 Crore           1
2.98 Crore           1
4.63 Crore           1
2.34 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
4.78 Crore           1
2.21 Crore           1
2.48 Crore           1
89.5 Lac             1
99.5 Lac             1
3.83 Crore           1
3.79 Crore           1
3.67 Crore           1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
4.79 Crore           1
6.25 Crore           1
35.5 Lac             1
2.11 Crore           1
1.06 Crore           1
4.94 Crore           1
10.75 Crore          1
81 Lac               1
26.1 Lac             1
9.14 Crore           1
8.35 Crore           1
20.5 Lac             1
17.5 Lac             1
24.5 Lac             1
10 Crore             1
6.1 Crore            1
5.75 Crore           1
2.77 Crore           1
7.56 Crore           1
79.9 Lac             1
68.5 Lac             1
85.5 Lac             1
93.75 Lac            1
94.25 Lac            1
80.5 Lac             1
2.97 Crore           1
29.99 Lac            1
4.86 Crore           1
2.62 Crore           1
52.5 Lac             1
90.5 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
47.5 Lac             1
4.52 Crore           1
8.44 Crore           1
1.84 Crore           1
13.2 Crore           1
4.16 Crore           1
1.74 Crore           1
4.21 Crore           1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
2.64 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
2.92 Crore           1
9.3 Crore            1
5.15 Crore           1
49.5 Lac             1
9.2 Crore            1
9.95 Crore           1
16 Lac               1
3.99 Crore           1
64.45 Lac            1
86.92 Lac            1
2.86 Crore           1
7.4 Crore            1
3.78 Crore           1
29.5 Lac             1
3.87 Crore           1
94.99 Lac            1
88.4 Lac             1
37.1 Lac             1
9 Crore              1
57 Lac               1
3.72 Crore           1
19 Lac               1
95.5 Lac             1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
96.07 Lac            1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

Comment: Need to remove rows where price = "Price on Request"

In [21]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1644,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1972,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2054,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2357,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2522,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2549,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2640,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2959,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2972,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2973,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [22]:
# Removing rows where price = "Price on Request"
df = df[df['price'] != 'Price on Request']

In [23]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [24]:
df['price'].value_counts()

price
1.25 Crore     79
1.1 Crore      61
1.4 Crore      60
1.2 Crore      59
1.5 Crore      59
90 Lac         58
1.3 Crore      57
95 Lac         53
2 Crore        51
1.75 Crore     47
1 Crore        46
1.6 Crore      43
1.35 Crore     41
1.9 Crore      40
1.55 Crore     40
75 Lac         38
1.65 Crore     38
1.8 Crore      37
1.7 Crore      37
80 Lac         36
2.2 Crore      34
1.15 Crore     33
50 Lac         33
1.45 Crore     31
85 Lac         31
1.05 Crore     30
2.5 Crore      29
60 Lac         29
40 Lac         29
2.1 Crore      26
45 Lac         26
65 Lac         25
35 Lac         23
1.85 Crore     23
2.35 Crore     23
3 Crore        22
70 Lac         21
2.25 Crore     20
55 Lac         20
3.5 Crore      19
2.3 Crore      18
2.4 Crore      18
30 Lac         17
2.65 Crore     16
1.38 Crore     15
2.6 Crore      15
2.45 Crore     14
3.4 Crore      14
2.15 Crore     14
82 Lac         13
78 Lac         13
38 Lac         13
92 Lac         13
2.7 Crore      13
1.32 Crore     13
3.25 Crore     13
42 Lac         12
1.95 Crore     12
5 Crore        12
2.8 Crore      12
1.42 Crore     12
88 Lac         11
25 Lac         11
32 Lac         11
1.08 Crore     11
1.28 Crore     10
26 Lac         10
87 Lac         10
1.12 Crore     10
1.78 Crore     10
2.55 Crore     10
28 Lac         10
2.85 Crore      9
1.68 Crore      9
1.72 Crore      9
3.45 Crore      9
99 Lac          9
2.05 Crore      9
4 Crore         9
36 Lac          9
22 Lac          9
48 Lac          8
20 Lac          8
27 Lac          8
86 Lac          8
4.25 Crore      8
2.75 Crore      8
1.26 Crore      8
6.5 Crore       8
1.54 Crore      8
1.18 Crore      8
1.76 Crore      8
3.2 Crore       8
6 Crore         8
98 Lac          8
56 Lac          8
72 Lac          7
39 Lac          7
1.29 Crore      7
2.9 Crore       7
1.27 Crore      7
1.36 Crore      7
46 Lac          7
3.7 Crore       7
1.99 Crore      7
1.19 Crore      7
1.02 Crore      7
97 Lac          7
3.3 Crore       7
79 Lac          7
1.16 Crore      6
2.95 Crore      6
1.14 Crore      6
96 Lac          6
3.05 Crore      6
1.51 Crore      6
1.49 Crore      6
71.5 Lac        6
4.1 Crore       6
1.07 Crore      6
5.5 Crore       6
1.59 Crore      6
3.65 Crore      6
21 Lac          6
54 Lac          6
1.34 Crore      6
1.01 Crore      6
37 Lac          6
3.35 Crore      6
43 Lac          6
3.9 Crore       6
1.13 Crore      6
1.39 Crore      6
1.98 Crore      6
1.24 Crore      5
6.75 Crore      5
1.33 Crore      5
29 Lac          5
1.47 Crore      5
2.22 Crore      5
3.75 Crore      5
93 Lac          5
1.44 Crore      5
1.69 Crore      5
1.91 Crore      5
49 Lac          5
1.82 Crore      5
1.83 Crore      5
1.79 Crore      5
1.62 Crore      5
2.29 Crore      5
1.92 Crore      5
1.93 Crore      5
4.5 Crore       5
68 Lac          5
24 Lac          5
66 Lac          5
1.43 Crore      5
2.12 Crore      5
64 Lac          5
2.78 Crore      5
1.17 Crore      5
58 Lac          4
28.5 Lac        4
1.71 Crore      4
1.22 Crore      4
4.3 Crore       4
1.48 Crore      4
6.15 Crore      4
3.1 Crore       4
7 Crore         4
4.85 Crore      4
89 Lac          4
73 Lac          4
31 Lac          4
1.66 Crore      4
67 Lac          4
1.23 Crore      4
36.5 Lac        4
33 Lac          4
1.58 Crore      4
1.31 Crore      4
5.9 Crore       4
2.09 Crore      4
41.5 Lac        4
5.6 Crore       4
74 Lac          4
1.37 Crore      4
1.52 Crore      4
5.25 Crore      4
1.73 Crore      4
62 Lac          4
3.6 Crore       4
1.77 Crore      4
1.64 Crore      4
3.95 Crore      4
4.75 Crore      3
3.8 Crore       3
1.04 Crore      3
2.28 Crore      3
2.03 Crore      3
1.09 Crore      3
2.08 Crore      3
1.67 Crore      3
1.57 Crore      3
2.36 Crore      3
91 Lac          3
4.8 Crore       3
2.51 Crore      3
3.15 Crore      3
2.24 Crore      3
52 Lac          3
69 Lac          3
83 Lac          3
1.21 Crore      3
2.01 Crore      3
94 Lac          3
1.41 Crore      3
72.5 Lac        3
51 Lac          3
1.63 Crore      3
5.8 Crore       3
84 Lac          3
34 Lac          3
2.33 Crore      3
3.85 Crore      3
2.79 Crore      3
1.88 Crore      3
64.5 Lac        3
3.49 Crore      3
4.2 Crore       3
47 Lac          3
56.2 Lac        2
3.55 Crore      2
7.5 Crore       2
27.1 Lac        2
11 Crore        2
4.55 Crore      2
2.87 Crore      2
2.14 Crore      2
52.56 Lac       2
87.5 Lac        2
2.99 Crore      2
1.56 Crore      2
2.26 Crore      2
2.58 Crore      2
2.57 Crore      2
2.04 Crore      2
3.29 Crore      2
2.52 Crore      2
8.5 Crore       2
8 Crore         2
2.17 Crore      2
71 Lac          2
4.49 Crore      2
59 Lac          2
77.5 Lac        2
53 Lac          2
5.7 Crore       2
2.23 Crore      2
6.2 Crore       2
53.5 Lac        2
5.2 Crore       2
27.75 Lac       2
4.7 Crore       2
88.5 Lac        2
14 Crore        2
2.02 Crore      2
2.41 Crore      2
3.32 Crore      2
4.6 Crore       2
3.21 Crore      2
25.5 Lac        2
4.26 Crore      2
4.45 Crore      2
98.5 Lac        2
1.46 Crore      2
2.13 Crore      2
31.5 Lac        2
2.91 Crore      2
1.87 Crore      2
41 Lac          2
3.19 Crore      1
5.31 Crore      1
4.95 Crore      1
4.02 Crore      1
97.04 Lac       1
37.5 Lac        1
68.85 Lac       1
3.23 Crore      1
2.69 Crore      1
2.54 Crore      1
54.8 Lac        1
3.98 Crore      1
2.44 Crore      1
9 Crore         1
82.5 Lac        1
61 Lac          1
94.5 Lac        1
29.8 Lac        1
6.02 Crore      1
7.9 Crore       1
15 Crore        1
7.8 Crore       1
1.97 Crore      1
39.5 Lac        1
11.25 Crore     1
7.15 Crore      1
2.82 Crore      1
54.99 Lac       1
8.25 Crore      1
4.67 Crore      1
31.75 Lac       1
3.87 Crore      1
2.37 Crore      1
2.63 Crore      1
1.11 Crore      1
6.44 Crore      1
98.1 Lac        1
55.5 Lac        1
95.75 Lac       1
3.46 Crore      1
3.63 Crore      1
3.39 Crore      1
5.4 Crore       1
55.6 Lac        1
66.99 Lac       1
23 Lac          1
5.49 Crore      1
6.3 Crore       1
2.98 Crore      1
4.63 Crore      1
2.34 Crore      1
6.16 Crore      1
5.3 Crore       1
2.72 Crore      1
4.78 Crore      1
2.21 Crore      1
2.48 Crore      1
89.5 Lac        1
99.5 Lac        1
3.83 Crore      1
4.4 Crore       1
3.79 Crore      1
35.5 Lac        1
71.2 Lac        1
27.5 Lac        1
23.5 Lac        1
4.79 Crore      1
79.9 Lac        1
3.67 Crore      1
1.06 Crore      1
26.1 Lac        1
4.94 Crore      1
9.14 Crore      1
8.35 Crore      1
81 Lac          1
10.75 Crore     1
17.5 Lac        1
24.5 Lac        1
10 Crore        1
5.75 Crore      1
2.11 Crore      1
6.1 Crore       1
2.77 Crore      1
7.56 Crore      1
6.25 Crore      1
68.5 Lac        1
93.75 Lac       1
85.5 Lac        1
2.97 Crore      1
94.25 Lac       1
29.99 Lac       1
80.5 Lac        1
2.62 Crore      1
53.2 Lac        1
90.5 Lac        1
52.5 Lac        1
65.5 Lac        1
47.5 Lac        1
42.5 Lac        1
2.61 Crore      1
20.5 Lac        1
1.74 Crore      1
4.21 Crore      1
4.52 Crore      1
8.44 Crore      1
1.84 Crore      1
4.16 Crore      1
5.15 Crore      1
2.92 Crore      1
13.2 Crore      1
2.64 Crore      1
2.38 Crore      1
2.49 Crore      1
63.4 Lac        1
2.06 Crore      1
97.5 Lac        1
2.07 Crore      1
44 Lac          1
2.32 Crore      1
1.86 Crore      1
85.75 Lac       1
87.99 Lac       1
9.3 Crore       1
4.86 Crore      1
9.95 Crore      1
86.99 Lac       1
9.2 Crore       1
49.5 Lac        1
86.92 Lac       1
3.99 Crore      1
16 Lac          1
2.86 Crore      1
7.4 Crore       1
3.78 Crore      1
98.88 Lac       1
29.5 Lac        1
94.99 Lac       1
88.4 Lac        1
64.45 Lac       1
37.1 Lac        1
57 Lac          1
3.72 Crore      1
19 Lac          1
95.5 Lac        1
70.85 Lac       1
7.52 Crore      1
40.3 Lac        1
96.07 Lac       1
32.5 Lac        1
2.96 Crore      1
1.53 Crore      1
26.9 Lac        1
26.5 Lac        1
73.53 Lac       1
89.77 Lac       1
62.5 Lac        1
Name: count, dtype: int64

Comments: Price are in different units. 'Lac' and 'Crore'. So, bringing all of the datapoints into same unit 'Crore'

In [25]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [26]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [27]:
df['price'].value_counts()

price
1.25     79
1.10     61
0.90     60
1.40     60
1.50     59
1.20     59
1.30     57
0.95     55
2.00     51
1.75     47
1.00     46
1.60     43
1.35     41
1.55     40
1.90     40
0.75     38
1.65     38
1.80     37
1.70     37
0.80     37
2.20     34
1.15     33
0.50     33
0.85     32
0.40     31
1.45     31
1.05     30
2.50     29
0.60     29
0.65     28
2.10     26
0.45     26
0.35     24
1.85     23
2.35     23
0.55     22
3.00     22
0.70     21
2.25     20
0.30     19
3.50     19
2.30     18
2.40     18
0.28     17
2.65     16
1.38     15
0.78     15
0.88     15
2.60     15
0.82     14
2.15     14
0.38     14
2.45     14
3.40     14
0.32     14
2.70     13
0.36     13
1.32     13
3.25     13
0.92     13
0.26     13
0.42     13
1.42     12
0.56     12
1.95     12
2.80     12
0.27     12
0.87     12
5.00     12
0.98     11
0.25     11
1.08     11
0.99     11
0.71     10
0.72     10
1.78     10
1.12     10
1.28     10
2.55     10
2.05      9
4.00      9
3.45      9
1.72      9
0.22      9
0.97      9
0.20      9
0.86      9
2.85      9
1.68      9
6.50      8
6.00      8
0.54      8
4.25      8
0.96      8
1.18      8
1.54      8
2.75      8
0.48      8
3.20      8
1.76      8
1.26      8
0.46      7
0.37      7
2.90      7
0.39      7
0.79      7
1.99      7
1.36      7
1.27      7
1.02      7
3.30      7
1.19      7
3.70      7
1.29      7
5.50      6
3.05      6
1.16      6
0.29      6
1.51      6
0.21      6
3.65      6
1.39      6
4.10      6
3.35      6
1.34      6
0.64      6
0.94      6
1.13      6
0.43      6
0.24      6
1.07      6
0.66      6
1.49      6
3.90      6
0.53      6
1.59      6
1.01      6
1.14      6
1.98      6
0.41      6
2.95      6
0.89      6
0.49      6
1.44      5
1.91      5
1.69      5
1.79      5
0.93      5
4.50      5
0.33      5
0.74      5
0.68      5
1.62      5
1.92      5
1.83      5
2.29      5
1.93      5
1.43      5
1.82      5
2.12      5
2.22      5
0.67      5
3.75      5
1.33      5
1.24      5
2.78      5
0.62      5
1.17      5
6.75      5
0.69      5
1.47      5
3.95      4
0.58      4
5.25      4
1.77      4
1.52      4
3.60      4
1.64      4
5.90      4
1.73      4
1.71      4
0.91      4
5.60      4
1.23      4
0.47      4
0.31      4
1.66      4
3.10      4
0.73      4
4.85      4
1.22      4
7.00      4
6.15      4
4.30      4
1.48      4
2.09      4
1.31      4
1.37      4
1.58      4
4.20      3
1.09      3
4.75      3
2.24      3
4.80      3
1.21      3
3.49      3
2.33      3
2.36      3
2.51      3
1.67      3
1.88      3
3.85      3
1.57      3
2.79      3
1.41      3
2.08      3
1.04      3
2.03      3
2.01      3
3.80      3
2.28      3
0.51      3
3.15      3
0.52      3
0.83      3
0.84      3
5.80      3
0.34      3
1.63      3
3.21      2
4.60      2
8.00      2
1.46      2
5.20      2
4.49      2
2.23      2
4.70      2
2.26      2
1.87      2
3.32      2
3.55      2
4.45      2
0.59      2
2.14      2
3.29      2
5.70      2
2.52      2
2.13      2
2.17      2
8.50      2
2.91      2
0.81      2
6.20      2
0.23      2
4.55      2
11.00     2
2.58      2
7.50      2
2.41      2
2.02      2
4.26      2
14.00     2
2.04      2
2.99      2
2.57      2
2.87      2
1.56      2
2.96      1
3.19      1
4.40      1
2.82      1
7.15      1
4.95      1
5.31      1
11.25     1
1.53      1
15.00     1
0.61      1
7.80      1
0.57      1
7.52      1
0.19      1
2.92      1
13.20     1
1.97      1
2.38      1
0.63      1
2.06      1
2.64      1
2.49      1
0.44      1
2.07      1
1.86      1
2.32      1
9.95      1
9.20      1
5.49      1
6.30      1
4.63      1
3.63      1
7.56      1
6.44      1
1.11      1
3.67      1
6.25      1
2.63      1
2.97      1
4.79      1
8.25      1
2.37      1
2.21      1
2.72      1
3.83      1
2.48      1
4.67      1
5.30      1
6.16      1
3.39      1
2.98      1
2.34      1
3.79      1
4.78      1
5.40      1
3.46      1
9.14      1
4.02      1
1.06      1
8.35      1
10.75     1
4.94      1
2.77      1
0.17      1
5.75      1
10.00     1
6.10      1
7.90      1
3.87      1
2.11      1
2.54      1
2.69      1
3.98      1
3.23      1
4.86      1
2.62      1
9.30      1
2.61      1
4.52      1
4.16      1
4.21      1
1.74      1
5.15      1
0.16      1
8.44      1
1.84      1
6.02      1
3.72      1
2.86      1
2.44      1
9.00      1
3.99      1
7.40      1
3.78      1
Name: count, dtype: int64

In [28]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [29]:
# price_per_sqft
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 12,500/sq.ft.     16
₹ 8,000/sq.ft.      16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 11,111/sq.ft.      6
₹ 6,578/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,600/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 10,714/sq.ft.      5
₹ 4,444/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 7,407/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 10,416/sq.ft.      4
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 13,913/sq.ft.      4
₹ 8,358/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 4,500/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 8,139/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 10,383/sq.ft.      4
₹ 5,660/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 8,474/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 6,250/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 7,812/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 7,496/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 10,204/sq.ft.      3
₹ 9,473/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 7,865/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 7,302/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 6,387/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 6,921/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 8,604/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 5,878/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 8,400/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 8,222/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 16,470/sq.ft.      3
₹ 7,750/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 7,056/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 6,667/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 7,541/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 6,644/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 11,412/sq.ft.      2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 12,777/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 7,878/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 19,747/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 5,674/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 10,699/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 8,903/sq.ft.       2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 6,190/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 5,463/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 7,884/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 8,433/sq.ft.       2
₹ 8,166/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 6,049/sq.ft.       2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 10,516/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 6,938/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 7,174/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 200,000/sq.ft.     2
₹ 6,382/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 8,424/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 9,791/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 9,565/sq.ft.       2
₹ 9,742/sq.ft.       2
₹ 8,324/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 8,536/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 6,406/sq.ft.       2
₹ 6,353/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 9,074/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,457/sq.ft.       2
₹ 13,709/sq.ft.      2
₹ 5,671/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 5,980/sq.ft.       2
₹ 5,820/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 8,100/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 5,599/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 6,588/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 6,571/sq.ft.       2
₹ 5,177/sq.ft.       2
₹ 14,303/sq.ft.      2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 9,620/sq.ft.       2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 9,433/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 7,863/sq.ft.       2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 6,076/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 9,642/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 8,609/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 10,601/sq.ft.      2
₹ 11,333/sq.ft.      2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 8,972/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 6,789/sq.ft.       2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 6,318/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 6,325/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,470/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 7,200/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 8,504/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 9,876/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,538/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,909/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 11,529/sq.ft.      2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 6,950/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 10,666/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 5,128/sq.ft.       2
₹ 6,338/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 6,702/sq.ft.       2
₹ 7,825/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 6,189/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 8,072/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 9,263/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 5,405/sq.ft.       2
₹ 58/sq.ft.          2
₹ 11,125/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 16,608/sq.ft.      2
₹ 13,430/sq.ft.      2
₹ 13,224/sq.ft.      2
₹ 5,681/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 8,159/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 5,786/sq.ft.       2
₹ 8,521/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 10,476/sq.ft.      2
₹ 8,453/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 11,516/sq.ft.      2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 7,574/sq.ft.       2
₹ 4,000/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 6,859/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 8,618/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 8,206/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 10,370/sq.ft.      2
₹ 13,953/sq.ft.      1
₹ 14,658/sq.ft.      1
₹ 15,982/sq.ft.      1
₹ 11,475/sq.ft.      1
₹ 3,713/sq.ft.       1
₹ 7,453/sq.ft.       1
₹ 9,370/sq.ft.       1
₹ 8,700/sq.ft.       1
₹ 6,033/sq.ft.       1
₹ 9,531/sq.ft.       1
₹ 5,720/sq.ft.       1
₹ 6,648/sq.ft.       1
₹ 7,910/sq.ft.       1
₹ 7,262/sq.ft.       1
₹ 16,445/sq.ft.      1
₹ 17,378/sq.ft.      1
₹ 9,380/sq.ft.       1
₹ 13,984/sq.ft.      1
₹ 15,262/sq.ft.      1
₹ 9,696/sq.ft.       1
₹ 7,194/sq.ft.       1
₹ 5,739/sq.ft.       1
₹ 8,404/sq.ft.       1
₹ 4,179/sq.ft.       1
₹ 22,222/sq.ft.      1
₹ 10,156/sq.ft.      1
₹ 7,227/sq.ft.       1
₹ 17,271/sq.ft.      1
₹ 4,106/sq.ft.       1
₹ 8,982/sq.ft.       1
₹ 7,872/sq.ft.       1
₹ 9,156/sq.ft.       1
₹ 4,108/sq.ft.       1
₹ 12,855/sq.ft.      1
₹ 9/sq.ft.           1
₹ 6,435/sq.ft.       1
₹ 26,936/sq.ft.      1
₹ 8,266/sq.ft.       1
₹ 7,006/sq.ft.       1
₹ 12,784/sq.ft.      1
₹ 8,734/sq.ft.       1
₹ 9,264/sq.ft.       1
₹ 24,300/sq.ft.      1
₹ 6,194/sq.ft.       1
₹ 18,331/sq.ft.      1
₹ 8,802/sq.ft.       1
₹ 9,519/sq.ft.       1
₹ 9,076/sq.ft.       1
₹ 14,680/sq.ft.      1
₹ 8,674/sq.ft.       1
₹ 8,349/sq.ft.       1
₹ 6,272/sq.ft.       1
₹ 14,632/sq.ft.      1
₹ 13,425/sq.ft.      1
₹ 6,485/sq.ft.       1
₹ 10,408/sq.ft.      1
₹ 14,084/sq.ft.      1
₹ 13,522/sq.ft.      1
₹ 10,257/sq.ft.      1
₹ 10,017/sq.ft.      1
₹ 10,888/sq.ft.      1
₹ 5,904/sq.ft.       1
₹ 10,483/sq.ft.      1
₹ 10,627/sq.ft.      1
₹ 7,779/sq.ft.       1
₹ 10,452/sq.ft.      1
₹ 15,124/sq.ft.      1
₹ 7,568/sq.ft.       1
₹ 4,375/sq.ft.       1
₹ 11,074/sq.ft.      1
₹ 10,626/sq.ft.      1
₹ 6,786/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 4,971/sq.ft.       1
₹ 6,715/sq.ft.       1
₹ 9,219/sq.ft.       1
₹ 8,986/sq.ft.       1
₹ 16,032/sq.ft.      1
₹ 13,058/sq.ft.      1
₹ 11,219/sq.ft.      1
₹ 6,881/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 10,172/sq.ft.      1
₹ 10,101/sq.ft.      1
₹ 14,783/sq.ft.      1
₹ 10,984/sq.ft.      1
₹ 10,031/sq.ft.      1
₹ 7,164/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 5,813/sq.ft.       1
₹ 11,178/sq.ft.      1
₹ 13,936/sq.ft.      1
₹ 11,854/sq.ft.      1
₹ 20,666/sq.ft.      1
₹ 7,988/sq.ft.       1
₹ 10,094/sq.ft.      1
₹ 9,002/sq.ft.       1
₹ 11,869/sq.ft.      1
₹ 18,688/sq.ft.      1
₹ 5,296/sq.ft.       1
₹ 7,679/sq.ft.       1
₹ 7,931/sq.ft.       1
₹ 10,309/sq.ft.      1
₹ 10,754/sq.ft.      1
₹ 10,306/sq.ft.      1
₹ 8,558/sq.ft.       1
₹ 8,124/sq.ft.       1
₹ 22,346/sq.ft.      1
₹ 3,671/sq.ft.       1
₹ 4,941/sq.ft.       1
₹ 10,924/sq.ft.      1
₹ 591/sq.ft.         1
₹ 7,066/sq.ft.       1
₹ 9,130/sq.ft.       1
₹ 7,068/sq.ft.       1
₹ 4,933/sq.ft.       1
₹ 23,344/sq.ft.      1
₹ 7,561/sq.ft.       1
₹ 6,256/sq.ft.       1
₹ 7,293/sq.ft.       1
₹ 16,230/sq.ft.      1
₹ 4,729/sq.ft.       1
₹ 6,751/sq.ft.       1
₹ 4,886/sq.ft.       1
₹ 17,543/sq.ft.      1
₹ 6,554/sq.ft.       1
₹ 14,358/sq.ft.      1
₹ 6,176/sq.ft.       1
₹ 5,329/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 6,022/sq.ft.       1
₹ 7,360/sq.ft.       1
₹ 10,656/sq.ft.      1
₹ 11,276/sq.ft.      1
₹ 8,850/sq.ft.       1
₹ 10,004/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 8,240/sq.ft.       1
₹ 12,791/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 6,113/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 7,321/sq.ft.       1
₹ 10,163/sq.ft.      1
₹ 4,869/sq.ft.       1
₹ 4,579/sq.ft.       1
₹ 5,443/sq.ft.       1
₹ 8,856/sq.ft.       1
₹ 8,840/sq.ft.       1
₹ 10,578/sq.ft.      1
₹ 3,516/sq.ft.       1
₹ 7,882/sq.ft.       1
₹ 13,575/sq.ft.      1
₹ 8,737/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 7,402/sq.ft.       1
₹ 9,701/sq.ft.       1
₹ 8,264/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 9,734/sq.ft.       1
₹ 8,970/sq.ft.       1
₹ 6,159/sq.ft.       1
₹ 4,923/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 8,297/sq.ft.       1
₹ 10,815/sq.ft.      1
₹ 7,769/sq.ft.       1
₹ 7,714/sq.ft.       1
₹ 11,989/sq.ft.      1
₹ 13,480/sq.ft.      1
₹ 8,522/sq.ft.       1
₹ 6,502/sq.ft.       1
₹ 9,459/sq.ft.       1
₹ 9,664/sq.ft.       1
₹ 9,102/sq.ft.       1
₹ 10,723/sq.ft.      1
₹ 5,931/sq.ft.       1
₹ 7,103/sq.ft.       1
₹ 8,040/sq.ft.       1
₹ 8,111/sq.ft.       1
₹ 4,868/sq.ft.       1
₹ 11,741/sq.ft.      1
₹ 4,458/sq.ft.       1
₹ 4,931/sq.ft.       1
₹ 11,190/sq.ft.      1
₹ 8,907/sq.ft.       1
₹ 6,926/sq.ft.       1
₹ 5,590/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 4,587/sq.ft.       1
₹ 5,041/sq.ft.       1
₹ 9,513/sq.ft.       1
₹ 10,773/sq.ft.      1
₹ 13,296/sq.ft.      1
₹ 7,547/sq.ft.       1
₹ 8,446/sq.ft.       1
₹ 7,760/sq.ft.       1
₹ 10,134/sq.ft.      1
₹ 10,071/sq.ft.      1
₹ 9,252/sq.ft.       1
₹ 6,998/sq.ft.       1
₹ 11,923/sq.ft.      1
₹ 6,979/sq.ft.       1
₹ 9,125/sq.ft.       1
₹ 9,583/sq.ft.       1
₹ 4,821/sq.ft.       1
₹ 6,346/sq.ft.       1
₹ 11,386/sq.ft.      1
₹ 11,423/sq.ft.      1
₹ 6,905/sq.ft.       1
₹ 4,927/sq.ft.       1
₹ 9,136/sq.ft.       1
₹ 15,360/sq.ft.      1
₹ 9,569/sq.ft.       1
₹ 9,639/sq.ft.       1
₹ 6,562/sq.ft.       1
₹ 6,077/sq.ft.       1
₹ 5,952/sq.ft.       1
₹ 8,095/sq.ft.       1
₹ 11,251/sq.ft.      1
₹ 8,123/sq.ft.       1
₹ 9,912/sq.ft.       1
₹ 11,209/sq.ft.      1
₹ 11,346/sq.ft.      1
₹ 5,076/sq.ft.       1
₹ 11,654/sq.ft.      1
₹ 13,989/sq.ft.      1
₹ 10,205/sq.ft.      1
₹ 3,664/sq.ft.       1
₹ 10,491/sq.ft.      1
₹ 9,371/sq.ft.       1
₹ 10,375/sq.ft.      1
₹ 12,009/sq.ft.      1
₹ 15,560/sq.ft.      1
₹ 12,272/sq.ft.      1
₹ 3,650/sq.ft.       1
₹ 9,856/sq.ft.       1
₹ 4,778/sq.ft.       1
₹ 5,413/sq.ft.       1
₹ 10,482/sq.ft.      1
₹ 5,265/sq.ft.       1
₹ 6,552/sq.ft.       1
₹ 6,768/sq.ft.       1
₹ 5,958/sq.ft.       1
₹ 11,497/sq.ft.      1
₹ 11,920/sq.ft.      1
₹ 13,921/sq.ft.      1
₹ 6,870/sq.ft.       1
₹ 9,016/sq.ft.       1
₹ 13,177/sq.ft.      1
₹ 14,838/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 6,137/sq.ft.       1
₹ 5,625/sq.ft.       1
₹ 7,010/sq.ft.       1
₹ 5,965/sq.ft.       1
₹ 11,442/sq.ft.      1
₹ 11,559/sq.ft.      1
₹ 6,556/sq.ft.       1
₹ 4,637/sq.ft.       1
₹ 17,691/sq.ft.      1
₹ 10,283/sq.ft.      1
₹ 17,729/sq.ft.      1
₹ 20,995/sq.ft.      1
₹ 19,943/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 15,901/sq.ft.      1
₹ 15,130/sq.ft.      1
₹ 11,525/sq.ft.      1
₹ 6,587/sq.ft.       1
₹ 10,697/sq.ft.      1
₹ 8,387/sq.ft.       1
₹ 8,487/sq.ft.       1
₹ 8,554/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 10,058/sq.ft.      1
₹ 5,950/sq.ft.       1
₹ 5,910/sq.ft.       1
₹ 9,843/sq.ft.       1
₹ 7,654/sq.ft.       1
₹ 9,218/sq.ft.       1
₹ 6,601/sq.ft.       1
₹ 10,903/sq.ft.      1
₹ 7,171/sq.ft.       1
₹ 6,914/sq.ft.       1
₹ 5,571/sq.ft.       1
₹ 10,418/sq.ft.      1
₹ 2,051/sq.ft.       1
₹ 2,666/sq.ft.       1
₹ 7,891/sq.ft.       1
₹ 8,347/sq.ft.       1
₹ 11,944/sq.ft.      1
₹ 6,951/sq.ft.       1
₹ 11,725/sq.ft.      1
₹ 14,795/sq.ft.      1
₹ 8,120/sq.ft.       1
₹ 8,557/sq.ft.       1
₹ 8,052/sq.ft.       1
₹ 4,404/sq.ft.       1
₹ 8,042/sq.ft.       1
₹ 7,951/sq.ft.       1
₹ 14,267/sq.ft.      1
₹ 15,317/sq.ft.      1
₹ 5,263/sq.ft.       1
₹ 4,646/sq.ft.       1
₹ 3,158/sq.ft.       1
₹ 7,299/sq.ft.       1
₹ 5,245/sq.ft.       1
₹ 6,340/sq.ft.       1
₹ 5,476/sq.ft.       1
₹ 5,861/sq.ft.       1
₹ 4,977/sq.ft.       1
₹ 3,600/sq.ft.       1
₹ 8,515/sq.ft.       1
₹ 6,051/sq.ft.       1
₹ 4,453/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 5,901/sq.ft.       1
₹ 7,764/sq.ft.       1
₹ 4,339/sq.ft.       1
₹ 8,627/sq.ft.       1
₹ 8,800/sq.ft.       1
₹ 14,142/sq.ft.      1
₹ 6,312/sq.ft.       1
₹ 15,800/sq.ft.      1
₹ 7,706/sq.ft.       1
₹ 22,108/sq.ft.      1
₹ 7,422/sq.ft.       1
₹ 7,604/sq.ft.       1
₹ 9,879/sq.ft.       1
₹ 4,250/sq.ft.       1
₹ 7,389/sq.ft.       1
₹ 4,716/sq.ft.       1
₹ 4,871/sq.ft.       1
₹ 11,179/sq.ft.      1
₹ 3,714/sq.ft.       1
₹ 3,666/sq.ft.       1
₹ 5,161/sq.ft.       1
₹ 8,669/sq.ft.       1
₹ 4,278/sq.ft.       1
₹ 4,512/sq.ft.       1
₹ 5,013/sq.ft.       1
₹ 4,325/sq.ft.       1
₹ 5,039/sq.ft.       1

Comment: we only need the number in price_per_sqft, need to remove extra contents

In [30]:
df[df['price_per_sqft'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
18,2 BHK Flat in Sector 93 Gurgaon,signature global orchard avenue 2,NaN,NaN,Carpet area: 577.11 (53.62 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"L-1104, Sector 93 Gurgaon, Gurgaon, Haryana",11st of 14 Floors,East,Under Construction,"['Huda Metro Station', 'V3S Sapphire Ninety', ...",Looking for a budget-Friendly 2 bhk flat in a ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2849,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# astype float bcoz it contains nan values
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [32]:
df['price_per_sqft'].value_counts()

price_per_sqft
10000.0     19
12500.0     16
8000.0      16
6666.0      13
5000.0      13
8333.0      12
7500.0      12
6000.0      11
8461.0       9
12000.0      8
7000.0       8
9000.0       7
11111.0      6
6578.0       6
9230.0       6
8888.0       6
8928.0       6
5500.0       6
11500.0      6
5600.0       5
11428.0      5
10714.0      5
4444.0       5
14242.0      5
7641.0       5
8571.0       5
8205.0       5
7142.0       5
16000.0      5
7407.0       5
4666.0       5
4615.0       5
6500.0       5
5556.0       5
5384.0       5
7692.0       5
10416.0      4
8432.0       4
4687.0       4
4814.0       4
8163.0       4
11666.0      4
7250.0       4
16666.0      4
13913.0      4
8358.0       4
7272.0       4
9090.0       4
9210.0       4
4500.0       4
8484.0       4
8139.0       4
4854.0       4
10383.0      4
5660.0       4
8500.0       4
8784.0       4
8445.0       4
7317.0       4
15384.0      4
8474.0       4
8043.0       4
8108.0       4
14418.0      4
6250.0       4
9822.0       4
15000.0      4
7812.0       4
6735.0       4
8787.0       4
13750.0      4
7496.0       4
13636.0      4
10204.0      3
9473.0       3
9011.0       3
7150.0       3
13392.0      3
8389.0       3
8532.0       3
6542.0       3
14430.0      3
8080.0       3
6593.0       3
5856.0       3
7400.0       3
14000.0      3
7865.0       3
4105.0       3
13000.0      3
9904.0       3
6470.0       3
5735.0       3
7179.0       3
9615.0       3
7302.0       3
9900.0       3
8181.0       3
8078.0       3
5319.0       3
7083.0       3
8215.0       3
5397.0       3
6387.0       3
5833.0       3
8620.0       3
10139.0      3
6921.0       3
10555.0      3
8604.0       3
11363.0      3
5878.0       3
8148.0       3
9500.0       3
5555.0       3
6421.0       3
6818.0       3
5238.0       3
14254.0      3
8400.0       3
13870.0      3
8222.0       3
7549.0       3
6086.0       3
7467.0       3
9972.0       3
7948.0       3
16969.0      3
16470.0      3
7750.0       3
7954.0       3
4210.0       3
4513.0       3
8886.0       3
7056.0       3
8750.0       3
8450.0       3
5325.0       3
4800.0       3
4820.0       3
10500.0      3
6667.0       3
6476.0       3
6404.0       3
10638.0      3
7541.0       3
8606.0       3
11000.0      3
6644.0       3
7586.0       3
11412.0      2
7608.0       2
6655.0       2
9978.0       2
15263.0      2
12777.0      2
7185.0       2
4327.0       2
5513.0       2
8632.0       2
5100.0       2
7878.0       2
15294.0      2
19747.0      2
6313.0       2
9105.0       2
6206.0       2
5896.0       2
5517.0       2
9022.0       2
12012.0      2
5674.0       2
13076.0      2
6987.0       2
9025.0       2
8834.0       2
9922.0       2
7359.0       2
8600.0       2
6927.0       2
20687.0      2
12212.0      2
13108.0      2
10699.0      2
15551.0      2
15416.0      2
9743.0       2
5839.0       2
6679.0       2
11765.0      2
17039.0      2
8846.0       2
16858.0      2
8279.0       2
5528.0       2
11505.0      2
8903.0       2
13270.0      2
19767.0      2
6190.0       2
9797.0       2
5463.0       2
11336.0      2
7884.0       2
7908.0       2
9007.0       2
8733.0       2
9672.0       2
8410.0       2
13383.0      2
14237.0      2
8517.0       2
8433.0       2
8166.0       2
7350.0       2
6373.0       2
18271.0      2
6049.0       2
8252.0       2
16985.0      2
6422.0       2
7631.0       2
4909.0       2
11726.0      2
4857.0       2
8897.0       2
7610.0       2
14785.0      2
12022.0      2
7945.0       2
10936.0      2
10516.0      2
16747.0      2
8290.0       2
5056.0       2
3911.0       2
9452.0       2
6333.0       2
8376.0       2
6315.0       2
6141.0       2
6053.0       2
4856.0       2
8519.0       2
16363.0      2
6938.0       2
5744.0       2
7174.0       2
8294.0       2
4307.0       2
3477.0       2
9306.0       2
6153.0       2
14683.0      2
8283.0       2
8411.0       2
9950.0       2
10553.0      2
200000.0     2
6382.0       2
6774.0       2
7987.0       2
9139.0       2
19882.0      2
8424.0       2
11727.0      2
10489.0      2
15195.0      2
5929.0       2
9791.0       2
5454.0       2
9589.0       2
11250.0      2
9565.0       2
9742.0       2
8324.0       2
7058.0       2
14285.0      2
19000.0      2
8536.0       2
8670.0       2
8412.0       2
8835.0       2
4761.0       2
6465.0       2
9020.0       2
5982.0       2
7716.0       2
6839.0       2
14615.0      2
6406.0       2
6353.0       2
6896.0       2
11715.0      2
9074.0       2
8024.0       2
7765.0       2
6402.0       2
8814.0       2
8031.0       2
9550.0       2
8457.0       2
13709.0      2
5671.0       2
8237.0       2
8974.0       2
11694.0      2
7223.0       2
5828.0       2
13343.0      2
5980.0       2
5820.0       2
6254.0       2
5588.0       2
9128.0       2
11574.0      2
5150.0       2
6455.0       2
10596.0      2
7014.0       2
15454.0      2
8100.0       2
8518.0       2
3695.0       2
4745.0       2
18518.0      2
12222.0      2
5599.0       2
9482.0       2
8756.0       2
6428.0       2
11992.0      2
6588.0       2
8947.0       2
5683.0       2
7449.0       2
5825.0       2
8305.0       2
6571.0       2
5177.0       2
14303.0      2
6692.0       2
5252.0       2
13928.0      2
9620.0       2
7850.0       2
7817.0       2
7490.0       2
7758.0       2
5564.0       2
12444.0      2
9433.0       2
5658.0       2
10651.0      2
7863.0       2
5808.0       2
4080.0       2
10237.0      2
6029.0       2
10545.0      2
6076.0       2
7751.0       2
5725.0       2
6825.0       2
6647.0       2
15500.0      2
9642.0       2
6243.0       2
7097.0       2
5038.0       2
5797.0       2
9286.0       2
8720.0       2
6510.0       2
9062.0       2
7585.0       2
7530.0       2
9677.0       2
8075.0       2
10526.0      2
8609.0       2
5189.0       2
7857.0       2
8006.0       2
9600.0       2
6983.0       2
5424.0       2
14545.0      2
10601.0      2
11333.0      2
7727.0       2
15998.0      2
8972.0       2
4400.0       2
14257.0      2
6789.0       2
9333.0       2
14214.0      2
6318.0       2
6739.0       2
11755.0      2
6325.0       2
7780.0       2
6061.0       2
9146.0       2
6429.0       2
7396.0       2
6377.0       2
10531.0      2
5470.0       2
6812.0       2
5521.0       2
7200.0       2
5641.0       2
11724.0      2
8504.0       2
10018.0      2
9876.0       2
11627.0      2
6538.0       2
8524.0       2
9909.0       2
8611.0       2
5882.0       2
8036.0       2
8035.0       2
13500.0      2
11529.0      2
9027.0       2
6420.0       2
6024.0       2
10384.0      2
6569.0       2
18000.0      2
6950.0       2
9449.0       2
5714.0       2
15151.0      2
6200.0       2
8053.0       2
6217.0       2
7846.0       2
7297.0       2
6178.0       2
8582.0       2
10599.0      2
10666.0      2
9259.0       2
9166.0       2
13769.0      2
5128.0       2
6338.0       2
13333.0      2
6702.0       2
7825.0       2
12782.0      2
6189.0       2
6616.0       2
8072.0       2
5614.0       2
5284.0       2
6209.0       2
7782.0       2
6811.0       2
9263.0       2
8310.0       2
6111.0       2
5899.0       2
14478.0      2
4651.0       2
6506.0       2
7796.0       2
9135.0       2
14583.0      2
5405.0       2
58.0         2
11125.0      2
9854.0       2
21538.0      2
5649.0       2
16608.0      2
13430.0      2
13224.0      2
5681.0       2
13281.0      2
8159.0       2
5111.0       2
6722.0       2
14800.0      2
5786.0       2
8521.0       2
6985.0       2
11028.0      2
6134.0       2
12250.0      2
10476.0      2
8453.0       2
5291.0       2
11516.0      2
18181.0      2
4271.0       2
16960.0      2
7574.0       2
4000.0       2
6686.0       2
17619.0      2
9851.0       2
11700.0      2
9182.0       2
6967.0       2
7225.0       2
7248.0       2
10603.0      2
7391.0       2
7627.0       2
13991.0      2
6551.0       2
6859.0       2
41245.0      2
8618.0       2
6597.0       2
8206.0       2
33198.0      2
10370.0      2
13953.0      1
14658.0      1
15982.0      1
11475.0      1
3713.0       1
7453.0       1
9370.0       1
8700.0       1
6033.0       1
9531.0       1
5720.0       1
6648.0       1
7910.0       1
7262.0       1
16445.0      1
17378.0      1
9380.0       1
13984.0      1
15262.0      1
9696.0       1
7194.0       1
5739.0       1
8404.0       1
4179.0       1
22222.0      1
10156.0      1
7227.0       1
17271.0      1
4106.0       1
8982.0       1
7872.0       1
9156.0       1
4108.0       1
12855.0      1
9.0          1
6435.0       1
26936.0      1
8266.0       1
7006.0       1
12784.0      1
8734.0       1
9264.0       1
24300.0      1
6194.0       1
18331.0      1
8802.0       1
9519.0       1
9076.0       1
14680.0      1
8674.0       1
8349.0       1
6272.0       1
14632.0      1
13425.0      1
6485.0       1
10408.0      1
14084.0      1
13522.0      1
10257.0      1
10017.0      1
10888.0      1
5904.0       1
10483.0      1
10627.0      1
7779.0       1
10452.0      1
15124.0      1
7568.0       1
4375.0       1
11074.0      1
10626.0      1
6786.0       1
11407.0      1
4971.0       1
6715.0       1
9219.0       1
8986.0       1
16032.0      1
13058.0      1
11219.0      1
6881.0       1
6849.0       1
10172.0      1
10101.0      1
14783.0      1
10984.0      1
10031.0      1
7164.0       1
11538.0      1
5813.0       1
11178.0      1
13936.0      1
11854.0      1
20666.0      1
7988.0       1
10094.0      1
9002.0       1
11869.0      1
18688.0      1
5296.0       1
7679.0       1
7931.0       1
10309.0      1
10754.0      1
10306.0      1
8558.0       1
8124.0       1
22346.0      1
3671.0       1
4941.0       1
10924.0      1
591.0        1
7066.0       1
9130.0       1
7068.0       1
4933.0       1
23344.0      1
7561.0       1
6256.0       1
7293.0       1
16230.0      1
4729.0       1
6751.0       1
4886.0       1
17543.0      1
6554.0       1
14358.0      1
6176.0       1
5329.0       1
11605.0      1
6022.0       1
7360.0       1
10656.0      1
11276.0      1
8850.0       1
10004.0      1
11061.0      1
8240.0       1
12791.0      1
6083.0       1
6113.0       1
6894.0       1
7321.0       1
10163.0      1
4869.0       1
4579.0       1
5443.0       1
8856.0       1
8840.0       1
10578.0      1
3516.0       1
7882.0       1
13575.0      1
8737.0       1
11963.0      1
7402.0       1
9701.0       1
8264.0       1
8707.0       1
9734.0       1
8970.0       1
6159.0       1
4923.0       1
8790.0       1
8297.0       1
10815.0      1
7769.0       1
7714.0       1
11989.0      1
13480.0      1
8522.0       1
6502.0       1
9459.0       1
9664.0       1
9102.0       1
10723.0      1
5931.0       1
7103.0       1
8040.0       1
8111.0       1
4868.0       1
11741.0      1
4458.0       1
4931.0       1
11190.0      1
8907.0       1
6926.0       1
5590.0       1
8920.0       1
4587.0       1
5041.0       1
9513.0       1
10773.0      1
13296.0      1
7547.0       1
8446.0       1
7760.0       1
10134.0      1
10071.0      1
9252.0       1
6998.0       1
11923.0      1
6979.0       1
9125.0       1
9583.0       1
4821.0       1
6346.0       1
11386.0      1
11423.0      1
6905.0       1
4927.0       1
9136.0       1
15360.0      1
9569.0       1
9639.0       1
6562.0       1
6077.0       1
5952.0       1
8095.0       1
11251.0      1
8123.0       1
9912.0       1
11209.0      1
11346.0      1
5076.0       1
11654.0      1
13989.0      1
10205.0      1
3664.0       1
10491.0      1
9371.0       1
10375.0      1
12009.0      1
15560.0      1
12272.0      1
3650.0       1
9856.0       1
4778.0       1
5413.0       1
10482.0      1
5265.0       1
6552.0       1
6768.0       1
5958.0       1
11497.0      1
11920.0      1
13921.0      1
6870.0       1
9016.0       1
13177.0      1
14838.0      1
11600.0      1
6137.0       1
5625.0       1
7010.0       1
5965.0       1
11442.0      1
11559.0      1
6556.0       1
4637.0       1
17691.0      1
10283.0      1
17729.0      1
20995.0      1
19943.0      1
8622.0       1
15901.0      1
15130.0      1
11525.0      1
6587.0       1
10697.0      1
8387.0       1
8487.0       1
8554.0       1
6778.0       1
10058.0      1
5950.0       1
5910.0       1
9843.0       1
7654.0       1
9218.0       1
6601.0       1
10903.0      1
7171.0       1
6914.0       1
5571.0       1
10418.0      1
2051.0       1
2666.0       1
7891.0       1
8347.0       1
11944.0      1
6951.0       1
11725.0      1
14795.0      1
8120.0       1
8557.0       1
8052.0       1
4404.0       1
8042.0       1
7951.0       1
14267.0      1
15317.0      1
5263.0       1
4646.0       1
3158.0       1
7299.0       1
5245.0       1
6340.0       1
5476.0       1
5861.0       1
4977.0       1
3600.0       1
8515.0       1
6051.0       1
4453.0       1
5666.0       1
5901.0       1
7764.0       1
4339.0       1
8627.0       1
8800.0       1
14142.0      1
6312.0       1
15800.0      1
7706.0       1
22108.0      1
7422.0       1
7604.0       1
9879.0       1
4250.0       1
7389.0       1
4716.0       1
4871.0       1
11179.0      1
3714.0       1
3666.0       1
5161.0       1
8669.0       1
4278.0       1
4512.0       1
5013.0       1
4325.0       1
5039.0       1
14009.0      1
5220.0       1
5719.0       1
6185.0       1
3692.0       1
14652.0      1
4591.0       1
6598.0       1
4694.0       1
5777.0       1
19444.0      1
7722.0       1
5584.0       1
11825.0      1
11794.0      1
6097.0       1
7907.0       1
6815.0       1
11131.0      1
11859.0      1
8588.0       1
5246.0       1
5925.0       1
7381.0       1
7978.0       1
6426.0       1
7971.0       1
6741.0       1
8082.0       1
1379.0       1
5333.0       1
8221.0       1
7029.0       1
11558.0      1
4.0          1
7926.0       1
7002.0       1
9538.0       1
57507.0      1
7489.0       1
5266.0       1
5250.0       1
8940.0       1
10743.0      1
7614.0       1
11142.0      1
7950.0       1
6694.0       1
16993.0      1
13300.0      1
15766.0      1
11447.0      1
8033.0       1
4117.0       1
4861.0       1
6690.0       1
8812.0       1
9091.0       1
4456.0       1
6680.0       1
6900.0       1
10380.0      1
3864.0       1
8666.0       1
5949.0       1
5367.0       1
50000.0      1
9846.0       1
5507.0       1
17488.0      1
22700.0      1
3352.0       1
4600.0       1
6842.0       1
7920.0       1
6550.0       1
12044.0      1
12912.0      1
5759.0       1
12437.0      1
6032.0       1
4603.0       1
11580.0      1
6919.0       1
12173.0      1
4938.0       1
6969.0       1
4792.0       1
5407.0       1
7893.0       1
6089.0       1
5491.0       1
6358.0       1
9227.0       1
7307.0       1
6389.0       1
6165.0       1
9310.0       1
6201.0       1
8298.0       1
6023.0       1
7886.0       1
5432.0       1
4786.0       1
4596.0       1
5214.0       1
4037.0       1
4657.0       1
5576.0       1
17548.0      1
6064.0       1
5257.0       1
12700.0      1
4700.0       1
6761.0       1
6505.0       1
4879.0       1
4033.0       1
6618.0       1
9595.0       1
5124.0       1
10539.0      1
15758.0      1
5055.0       1
9678.0       1
14460.0      1
13652.0      1
5441.0       1
4750.0       1
13632.0      1
5583.0       1
8367.0       1
15267.0      1
6526.0       1
14551.0      1
4470.0       1
12408.0      1
14754.0      1
8990.0       1
5261.0       1
7754.0       1
13975.0      1
15178.0      1
5933.0       1
13126.0      1
2638.0       1
4942.0       1
4673.0       1
6007.0       1
4602.0       1
4345.0       1
6168.0       1
21922.0      1
4736.0       1
16768.0      1
1384.0       1
5826.0       1
5510.0       1
6577.0       1
8656.0       1
5412.0       1
7308.0       1
16500.0      1
13974.0      1
3789.0       1
8754.0       1
6100.0       1
4867.0       1
7594.0       1
7242.0       1
8653.0       1
6800.0       1
6054.0       1
13502.0      1
5066.0       1
8639.0       1
5701.0       1
7119.0       1
10159.0      1
6903.0       1
15918.0      1
18459.0      1
10276.0      1
6082.0       1
25000.0      1
9586.0       1
6742.0       1
5522.0       1
6105.0       1
4367.0       1
20664.0      1
5966.0       1
11141.0      1
4706.0       1
6586.0       1
6779.0       1
7434.0       1
8250.0       1
5279.0       1
14381.0      1
14723.0      1
11379.0      1
18636.0      1
4522.0       1
7059.0       1
11594.0      1
10563.0      1
6875.0       1
8794.0       1
29545.0      1
15644.0      1
17241.0      1
6136.0       1
8872.0       1
9868.0       1
22388.0      1
9142.0       1
4842.0       1
3368.0       1
5937.0       1
5102.0       1
11844.0      1
947.0        1
7246.0       1
7768.0       1
4837.0       1
9745.0       1
5479.0       1
4478.0       1
13608.0      1
8056.0       1
10909.0      1
9041.0       1
13379.0      1
6388.0       1
3142.0       1
6035.0       1
6645.0       1
6808.0       1
8421.0       1
20707.0      1
11094.0      1
7917.0       1
5621.0       1
18392.0      1
4219.0       1
9714.0       1
8953.0       1
12489.0      1
14379.0      1
8026.0       1
12420.0      1
8509.0       1
15826.0      1
13340.0      1
6728.0       1
16653.0      1
16139.0      1
6467.0       1
9474.0       1
12911.0      1
6535.0       1
10215.0      1
10211.0      1
9375.0       1
9236.0       1
7190.0       1
6170.0       1
7929.0       1
4681.0       1
15348.0      1
41666.0      1
12592.0      1
7567.0       1
4098.0       1
9532.0       1
11249.0      1
10245.0      1
8494.0       1
10167.0      1
26875.0      1
7862.0       1
13700.0      1
20000.0      1
9223.0       1
10906.0      1
9033.0       1
20816.0      1
8145.0       1
11917.0      1
14541.0      1
9698.0       1
11034.0      1
3847.0       1
7964.0       1
10967.0      1
12264.0      1
9050.0       1
11583.0      1
16411.0      1
8695.0       1
7807.0       1
7623.0       1
8269.0       1
6475.0       1
14420.0      1
4166.0       1
4373.0       1
8319.0       1
8231.0       1
5195.0       1
5776.0       1
14612.0      1
5703.0       1
9448.0       1
13478.0      1
15765.0      1
4011.0       1
7763.0       1
8843.0       1
12059.0      1
13739.0      1
12859.0      1
9038.0       1
6660.0       1
19333.0      1
7426.0       1
8375.0       1
6622.0       1
10105.0      1
25925.0      1
12820.0      1
14525.0      1
7394.0       1
17615.0      1
5495.0       1
6478.0       1
11633.0      1
7294.0       1
6775.0       1
6561.0       1
8917.0       1
5390.0       1
9066.0       1
4301.0       1
4521.0       1
15546.0      1
6724.0       1
5855.0       1
21519.0      1
4476.0       1
8837.0       1
8677.0       1
17500.0      1
18090.0      1
5954.0       1
4518.0       1
6628.0       1
10698.0      1
10833.0      1
7633.0       1
6016.0       1
8827.0       1
6408.0       1
6452.0       1
15200.0      1
5198.0       1
4260.0       1
5120.0       1
7529.0       1
6590.0       1
5656.0       1
9395.0       1
7826.0       1
14322.0      1
8278.0       1
9641.0       1
4134.0       1
6040.0       1
7355.0       1
16256.0      1
10057.0      1
46917.0      1
14874.0      1
8527.0       1
8151.0       1
13369.0      1
10200.0      1
8759.0       1
8839.0       1
12152.0      1
13253.0      1
12190.0      1
4370.0       1
4355.0       1
7734.0       1
5418.0       1
11358.0      1
12599.0      1
13678.0      1
23091.0      1
4836.0       1
7646.0       1
6961.0       1
4528.0       1
8580.0       1
13571.0      1
11686.0      1
6585.0       1
7230.0       1
6453.0       1
5973.0       1
15185.0      1
6826.0       1
5004.0       1
13878.0      1
14557.0      1
12325.0      1
9133.0       1
6819.0       1
17285.0      1
13929.0      1
6514.0       1
6580.0       1
16750.0      1
16580.0      1
10334.0      1
14983.0      1
11860.0      1
9051.0       1
9622.0       1
13528.0      1
4864.0       1
5499.0       1
10595.0      1
8646.0       1
10461.0      1
10080.0      1
8172.0       1
12571.0      1
11914.0      1
9266.0       1
12544.0      1
12235.0      1
14079.0      1
6713.0       1
13790.0      1
10814.0      1
7220.0       1
12627.0      1
7392.0       1
12818.0      1
16050.0      1
18500.0      1
9528.0       1
13125.0      1
5788.0       1
13690.0      1
28266.0      1
7869.0       1
13495.0      1
18400.0      1
17721.0      1
5530.0       1

In [33]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [34]:
# bedrooms
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [35]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2849,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2850,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2922,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Comment: Those rows which contains NaN in bedRoom also contains NaN in other columns. So removing those rows.

In [36]:
df = df[~df['bedRoom'].isnull()]

In [37]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [38]:
# only need the number and since no NaN values, so astype('int')
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [39]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [40]:
# bathroom
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [41]:
df['bathroom'].isnull().sum()

np.int64(0)

In [42]:
# only need the number and since no NaN values, so astype('int')
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [43]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [44]:
# balcony
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

Comment: 'balcony' need only number, so need to remove extra text. Also since 3+ is there, can't convert it to int or float, need to keep it in string format only.

In [45]:
df['balcony'].isnull().sum()

np.int64(0)

In [46]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [47]:
df['balcony'].value_counts()

balcony
3     974
3+    862
2     749
1     315
0      97
Name: count, dtype: int64

In [48]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [49]:
# additionalRoom
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [50]:
df['additionalRoom'].value_counts().shape

(49,)

In [51]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

Comment: Many types of extra rooms like puja, servant... also too many NaN values

In [52]:
# replacing NaN values with 'not available' string
df['additionalRoom'].fillna('not available',inplace=True)

/tmp/ipykernel_5776/591493101.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [53]:
# converting content of additionalRoom column in lowercase
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [54]:
df['additionalRoom'].value_counts()

additionalRoom
not available                                    1305
servant room                                      629
study room                                        232
others                                            179
pooja room                                        132
study room,servant room                            81
store room                                         76
pooja room,servant room                            60
servant room,others                                52
servant room,pooja room                            30
study room,others                                  27
pooja room,study room,servant room,others          25
pooja room,study room,servant room                 24
servant room,store room                            19
pooja room,study room                              13
pooja room,study room,servant room,store room      12
servant room,study room                             8
study room,pooja room                               8
study room,servant room,store room                  7
pooja room,servant room,others                      6
servant room,study room,pooja room,store room       6
pooja room,store room                               6
others,servant room                                 6
pooja room,others                                   6
study room,servant room,others                      5
pooja room,study room,store room                    4
pooja room,store room,study room,servant room       4
study room,pooja room,store room                    3
store room,servant room                             3
servant room,pooja room,study room,store room       3
servant room,others,pooja room                      2
study room,servant room,pooja room,store room       2
servant room,study room,store room                  2
study room,pooja room,servant room                  2
servant room,others,store room,pooja room           2
pooja room,study room,others                        2
store room,pooja room,servant room                  1
pooja room,study room,store room,servant room       1
pooja room,servant room,study room,store room       1
servant room,pooja room,store room                  1
study room,servant room,store room,pooja room       1
study room,servant room,pooja room                  1
servant room,pooja room,store room,study room       1
study room,store room                               1
store room,study room                               1
servant room,pooja room,study room                  1
servant room,study room,pooja room                  1
others,study room                                   1
servant room,study room,others                      1
store room,pooja room                               1
Name: count, dtype: int64

In [55]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [56]:
# floor num
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
8th   of 19 Floors          24
5th   of 14 Floors          24
3rd   of 14 Floors          24
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
11st   of 14 Floors         23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
7th   of 15 Floors          17
Ground of 1 Floors          17
7th   of 18 Floors          17
10th   of 18 Floors         17
12nd   of 12 Floors         17
9th   of 13 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
2nd   of 12 Floors          15
6th   of 12 Floors          15
9th   of 15 Floors          15
1st   of 3 Floors           15
6th   of 19 Floors          14
1st   of 2 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
6th   of 10 Floors          13
5th   of 5 Floors           13
Ground of 4 Floors          13
7th   of 7 Floors           13
10th   of 10 Floors         12
6th   of 15 Floors          12
8th   of 12 Floors          11
16th   of 19 Floors         11
8th   of 8 Floors           11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
17th   of 17 Floors         11
4th   of 10 Floors          11
6th   of 6 Floors           11
4th   of 13 Floors          11
4th   of 12 Floors          10
6th   of 13 Floors          10
3rd   of 5 Floors           10
7th   of 26 Floors          10
2nd   of 19 Floors          10
7th   of 13 Floors          10
1st   of 26 Floors          10
10th   of 12 Floors         10
7th   of 21 Floors          10
12nd   of 18 Floors         10
4th   of 15 Floors          10
3rd   of 9 Floors           10
15th   of 29 Floors          9
3rd   of 12 Floors           9
8th   of 22 Floors           9
18th   of 19 Floors          9
14th   of 19 Floors          9
9th   of 20 Floors           9
13rd   of 14 Floors          9
8th   of 15 Floors           9
7th   of 17 Floors           9
14th   of 15 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
6th   of 26 Floors           9
7th   of 12 Floors           9
6th   of 16 Floors           9
3rd   of 15 Floors           8
9th   of 18 Floors           8
5th   of 13 Floors           8
3rd   of 19 Floors           8
1st   of 19 Floors           8
12nd   of 24 Floors          8
8th   of 24 Floors           8
9th   of 12 Floors           8
2nd   of 15 Floors           8
12nd   of 26 Floors          8
10th   of 13 Floors          8
8th   of 26 Floors           8
8th   of 13 Floors           8
12nd   of 19 Floors          8
10th   of 17 Floors          8
4th   of 26 Floors           8
2nd   of 5 Floors            8
2nd   of 8 Floors            8
5th   of 9 Floors            8
14th   of 24 Floors          8
2nd   of 10 Floors           7
13rd   of 13 Floors          7
8th   of 21 Floors           7
7th   of 19 Floors           7
12nd   of 15 Floors          7
9th   of 19 Floors           7
5th   of 29 Floors           7
11st   of 24 Floors          7
2nd   of 13 Floors           7
16th   of 16 Floors          7
8th   of 10 Floors           7
12nd   of 13 Floors          7
1st   of 13 Floors           7
4th   of 19 Floors           7
2nd   of 17 Floors           7
11st   of 11 Floors          7
5th   of 20 Floors           7
11st   of 13 Floors          7
10th   of 21 Floors          7
11st   of 26 Floors          7
5th   of 10 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
11st   of 12 Floors          6
7th   of 20 Floors           6
16th   of 18 Floors          6
5th   of 25 Floors           6
5th   of 22 Floors           6
14th   of 27 Floors          6
12nd   of 22 Floors          6
Ground of 16 Floors          6
17th   of 19 Floors          6
1st   of 10 Floors           6
2nd   of 20 Floors           6
10th   of 15 Floors          6
19th   of 19 Floors          6
15th   of 15 Floors          6
10th   of 20 Floors          6
3rd   of 25 Floors           6
11st   of 19 Floors          6
Ground of 3 Floors           6
6th   of 9 Floors            6
1st   of 5 Floors            6
10th   of 29 Floors          6
4th   of 18 Floors           6
9th   of 30 Floors           5
9th   of 11 Floors           5
12nd   of 21 Floors          5
14th   of 16 Floors          5
4th   of 27 Floors           5
Ground of 19 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 21 Floors          5
1st   of 15 Floors           5
18th   of 29 Floors          5
10th   of 27 Floors          5
7th   of 8 Floors            5
15th   of 18 Floors          5
8th   of 9 Floors            5
6th   of 11 Floors           5
4th   of 9 Floors            5
11st   of 25 Floors          5
6th   of 20 Floors           5
16th   of 26 Floors          5
8th   of 30 Floors           5
10th   of 25 Floors          5
15th   of 28 Floors          5
12nd   of 29 Floors          5
1st   of 12 Floors           5
11st   of 16 Floors          5
11st   of 29 Floors          5
Ground of 21 Floors          5
7th   of 27 Floors           5
11st   of 30 Floors          5
14th   of 29 Floors          5
5th   of 19 Floors           5
1st   of 7 Floors            5
4th   of 22 Floors           5
6th   of 17 Floors           5
9th   of 22 Floors           5
3rd   of 20 Floors           5
5th   of 8 Floors            5
3rd   of 10 Floors           4
3rd   of 17 Floors           4
14th   of 21 Floors          4
3rd   of 22 Floors           4
7th   of 10 Floors           4
18th   of 32 Floors          4
15th   of 32 Floors          4
19th   of 40 Floors          4
11st   of 20 Floors          4
14th   of 18 Floors          4
23rd   of 26 Floors          4
11st   of 17 Floors          4
7th   of 11 Floors           4
13rd   of 19 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
20th   of 26 Floors          4
19th   of 24 Floors          4
13rd   of 21 Floors          4
Ground of 13 Floors          4
5th   of 24 Floors           4
8th   of 20 Floors           4
25th   of 25 Floors          4
17th   of 26 Floors          4
2nd   of 16 Floors           4
20th   of 20 Floors          4
2nd   of 11 Floors           4
11st   of 15 Floors          4
5th   of 16 Floors           4
2nd   of 9 Floors            4
17th   of 18 Floors          4
6th   of 30 Floors           4
5th   of 23 Floors           4
Ground of 17 Floors          4
3rd   of 11 Floors           4
22nd   of 30 Floors          4
22nd   of 24 Floors          4
14th   of 17 Floors          4
15th   of 23 Floors          4
1st   of 18 Floors           4
7th   of 9 Floors            4
17th   of 24 Floors          4
15th   of 16 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
12nd   of 16 Floors          4
4th   of 8 Floors            4
13rd   of 25 Floors          4
7th   of 24 Floors           4
15th   of 26 Floors          4
9th   of 10 Floors           4
12nd   of 30 Floors          4
6th   of 22 Floors           3
7th   of 23 Floors           3
8th   of 11 Floors           3
16th   of 20 Floors          3
26th   of 30 Floors          3
13rd   of 15 Floors          3
9th   of 16 Floors           3
10th   of 30 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
5th   of 30 Floors           3
12nd   of 27 Floors          3
18th   of 18 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
3rd   of 8 Floors            3
9th   of 40 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
3rd   of 26 Floors           3
6th   of 23 Floors           3
6th   of 29 Floors           3
18th   of 26 Floors          3
23rd   of 23 Floors          3
21st   of 22 Floors          3
4th   of 16 Floors           3
11st   of 27 Floors          3
2nd   of 22 Floors           3
10th   of 23 Floors          3
6th   of 21 Floors           3
14th   of 32 Floors          3
4th   of 21 Floors           3
21st   of 24 Floors          3
30th   of 32 Floors          3
24th   of 24 Floors          3
5th   of 17 Floors           3
19th   of 21 Floors          3
12nd   of 23 Floors          3
5th   of 26 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
15th   of 20 Floors          3
3rd   of 16 Floors           3
17th   of 30 Floors          3
10th   of 16 Floors          3
8th   of 17 Floors           3
2nd   of 26 Floors           3
9th   of 21 Floors           3
19th   of 29 Floors          3
Ground of 18 Floors          3
8th   of 25 Floors           3
15th   of 39 Floors          3
6th   of 8 Floors            3
8th   of 40 Floors           3
18th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 29 Floors           3
17th   of 29 Floors          3
17th   of 20 Floors          3
4th   of 20 Floors           3
10th   of 28 Floors          3
19th   of 30 Floors          3
27th   of 27 Floors          3
1st   of 17 Floors           2
3rd   of 33 Floors           2
18th   of 21 Floors          2
14th   of 28 Floors          2
16th   of 32 Floors          2
16th   of 27 Floors          2
16th   of 24 Floors          2
2nd   of 6 Floors            2
19th   of 27 Floors          2
7th   of 30 Floors           2
13rd   of 30 Floors          2
10th   of 40 Floors          2
13rd   of 20 Floors          2
2nd   of 28 Floors           2
15th   of 31 Floors          2
27th   of 29 Floors          2
24th   of 30 Floors          2
Ground of 23 Floors          2
4th   of 11 Floors           2
9th   of 29 Floors           2
19th   of 20 Floors          2
2nd   of 24 Floors           2
14th   of 20 Floors          2
43   of 47 Floors            2
1st   of 22 Floors           2
16th   of 30 Floors          2
25th   of 29 Floors          2
23rd   of 29 Floors          2
20th   of 23 Floors          2
9th   of 17 Floors           2
11st   of 23 Floors          2
8th   of 23 Floors           2
8th   of 29 Floors           2
3rd   of 32 Floors           2
10th   of 32 Floors          2
2nd   of 7 Floors            2
4th   of 5 Floors            2
Ground of 51 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
13rd   of 40 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 21 Floors          2
7th   of 29 Floors           2
8th   of 32 Floors           2
6th   of 31 Floors           2
12nd   of 25 Floors          2
1st   of 24 Floors           2
39th   of 40 Floors          2
9th   of 28 Floors           2
16th   of 34 Floors          2
10th   of 22 Floors          2
7th   of 36 Floors           2
3rd   of 24 Floors           2
2nd   of 18 Floors           2
2nd   of 40 Floors           2
3rd   of 27 Floors           2
2nd   of 21 Floors           2
10th   of 11 Floors          2
2nd   of 25 Floors           2
1st   of 20 Floors           2
1st   of 30 Floors           2
22nd   of 25 Floors          2
1st   of 8 Floors            2
23rd   of 34 Floors          2
18th   of 24 Floors          2
Lower Ground of 4 Floors     2
4th   of 34 Floors           2
20th   of 25 Floors          2
7th   of 22 Floors           2
3rd   of 29 Floors           2
11st   of 21 Floors          2
8th   of 28 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
15th   of 17 Floors          2
9th   of 27 Floors           2
20th   of 22 Floors          2
1st   of 16 Floors           2
16th   of 36 Floors          2
5th   of 11 Floors           2
40th   of 40 Floors          2
15th   of 45 Floors          2
17th   of 33 Floors          2
31st   of 40 Floors          1
18th   of 20 Floors          1
3rd   of 31 Floors           1
27th   of 30 Floors          1
34th   of 34 Floors          1
5th   of 36 Floors           1
18th   of 35 Floors          1
17th   of 31 Floors          1
21st   of 23 Floors          1
Ground of 5 Floors           1
Ground of 6 Floors           1
Basement of 13 Floors        1
18th   of 22 Floors          1
17th   of 22 Floors          1
24th   of 36 Floors          1
3rd   of 36 Floors           1
5th   of 6 Floors            1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 35 Floors           1
Ground of 2 Floors           1
10th   of 33 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
20th   of 34 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
15th   of 27 Floors          1
11st   of 22 Floors          1
Ground of 11 Floors          1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
35th   of 51 Floors          1
22nd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
3rd   of 40 Floors           1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
18th   of 40 Floors          1
6th   of 25 Floors           1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 30 Floors          1
18th   of 51 Floors          1
24th   of 27 Floors          1
19th   of 22 Floors          1
8th   of 31 Floors           1
33rd   of 48 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
Ground of 24 Floors          1
7th   of 25 Floors           1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
9th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
10th   of 39 Floors          1
21st   of 26 Floors          1
1st   of 44 Floors           1
7th   of 42 Floors           1
25th   of 36 Floors          1
21st   of 28 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
29th   of 31 Floors          1
22nd   of 40 Floors          1
16th   of 41 Floors          1
7th   of 40 Floors           1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
19th   of 32 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
14th   of 41 Floors          1
Ground of 29 Floors          1
22nd   of 26 Floors          1
32nd   of 55 Floors          1
Ground of 40 Floors          1
13rd   of 22 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
24th   of 31 Floors          1
24th   of 51 Floors          1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
29th   of 39 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [57]:
df['floorNum'].isnull().sum()

np.int64(2)

In [58]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2766,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [59]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [60]:
df['floorNum'].value_counts()

floorNum
2     258
3     248
1     223
4     203
8     200
7     188
10    185
6     185
5     172
9     171
12    160
0     133
14    117
11    115
15     83
16     53
17     51
13     43
18     38
19     34
20     25
21     15
23     15
22     14
24     11
25      9
27      7
26      5
30      5
31      4
28      4
33      3
29      3
32      2
43      2
35      2
39      2
40      2
34      2
38      1
44      1
45      1
Name: count, dtype: int64

In [61]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2766,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3016
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   society          2997 non-null   object
 2   price            2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2997 non-null   object
 5   bedRoom          2997 non-null   int64
 6   bathroom         2997 non-null   int64
 7   balcony          2997 non-null   object
 8   additionalRoom   2997 non-null   object
 9   address          2991 non-null   object
 10  floorNum         2995 non-null   object
 11  facing           2123 non-null   object
 12  agePossession    2996 non-null   object
 13  nearbyLocations  2906 non-null   object
 14  description      2997 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2590 non-null   object
 17  rating           2668 non-null   object
dtypes: float64(2), int64(2), object(14)
memory usage: 444.9+ KB

In [63]:
# updating 181th index floorNum from description
df.at[181,'floorNum'] = '6'

In [64]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2766,2 BHK Flat in Sector 78 Gurgaon,nan,0.6,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [65]:
# Dropping row 2766 since NaN value in floorNum
df = df.drop(2766)
df[df['floorNum'].isnull()]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   society          2996 non-null   object
 2   price            2995 non-null   float64
 3   price_per_sqft   2995 non-null   float64
 4   areaWithType     2996 non-null   object
 5   bedRoom          2996 non-null   int64
 6   bathroom         2996 non-null   int64
 7   balcony          2996 non-null   object
 8   additionalRoom   2996 non-null   object
 9   address          2990 non-null   object
 10  floorNum         2996 non-null   object
 11  facing           2123 non-null   object
 12  agePossession    2995 non-null   object
 13  nearbyLocations  2906 non-null   object
 14  description      2996 non-null   object
 15  furnishDetails   2199 non-null   object
 16  features         2590 non-null   object
 17  rating           2667 non-null   object
dtypes: float64(2), int64(2), object(14)
memory usage: 444.7+ KB

In [67]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [68]:
# facing
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [69]:
df['facing'].isnull().sum()

np.int64(873)

In [70]:
df['facing'].fillna('NA',inplace=True)

/tmp/ipykernel_5776/3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [71]:
df['facing'].value_counts()

facing
NA            873
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

Comment: From 'price' and 'price_per_sqft' column let's calculate the area

In [72]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [73]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [74]:
df['area'].value_counts()

area
1650.0      53
1950.0      43
2000.0      33
1350.0      32
2400.0      24
2150.0      21
1900.0      20
1800.0      20
1300.0      20
1550.0      20
1578.0      19
1150.0      17
1450.0      17
2200.0      17
1400.0      17
600.0       16
1200.0      16
1500.0      16
1000.0      16
1930.0      15
1760.0      14
1640.0      14
1250.0      14
750.0       14
700.0       14
900.0       14
2350.0      14
1750.0      14
2010.0      13
1850.0      13
1600.0      13
2300.0      13
1975.0      13
2191.0      13
2100.0      13
650.0       12
3150.0      12
1423.0      12
1103.0      12
950.0       12
2812.0      12
2408.0      12
1245.0      11
1366.0      11
1997.0      11
2290.0      11
915.0       11
1100.0      11
1385.0      10
1929.0      10
2450.0      10
1050.0       9
1081.0       9
1700.0       9
1310.0       9
2660.0       9
2003.0       9
850.0        9
1360.0       9
990.0        8
3400.0       8
1380.0       8
2358.0       8
2600.0       8
1538.0       8
1620.0       8
1790.0       8
1530.0       8
2103.0       8
1630.0       8
1490.0       8
500.0        7
800.0        7
2250.0       7
1180.0       7
2950.0       7
2215.0       7
1811.0       7
482.0        7
1572.0       7
2132.0       7
1990.0       7
3000.0       7
2361.0       7
1660.0       6
1534.0       6
450.0        6
2095.0       6
2025.0       6
735.0        6
2727.0       6
1825.0       6
1976.0       6
1875.0       6
2500.0       6
1745.0       6
2800.0       6
1815.0       6
2149.0       6
1430.0       6
2125.0       6
2047.0       6
1780.0       6
4200.0       6
576.0        6
1741.0       6
822.0        6
1365.0       6
2120.0       6
2875.0       6
1735.0       6
1960.0       6
2364.0       6
1565.0       6
1326.0       6
554.0        5
1260.0       5
1725.0       5
1895.0       5
1549.0       5
1447.0       5
1480.0       5
1690.0       5
1130.0       5
3500.0       5
1342.0       5
1755.0       5
301.0        5
489.0        5
1727.0       5
1828.0       5
1210.0       5
1225.0       5
2605.0       5
1415.0       5
2588.0       5
1671.0       5
2355.0       5
645.0        5
1852.0       5
1295.0       5
2093.0       5
2040.0       5
1105.0       5
1508.0       5
1120.0       5
2092.0       5
2545.0       5
3200.0       4
2802.0       4
1526.0       4
1818.0       4
569.0        4
1364.0       4
1860.0       4
1579.0       4
1744.0       4
1261.0       4
1439.0       4
583.0        4
1262.0       4
1920.0       4
1935.0       4
1806.0       4
1765.0       4
644.0        4
567.0        4
1440.0       4
481.0        4
2048.0       4
1425.0       4
1523.0       4
1537.0       4
1457.0       4
1276.0       4
1822.0       4
1692.0       4
2298.0       4
1647.0       4
602.0        4
1910.0       4
1720.0       4
591.0        4
2585.0       4
595.0        4
2905.0       4
2700.0       4
1370.0       4
2217.0       4
1433.0       4
925.0        4
2685.0       4
1980.0       4
640.0        4
1320.0       4
3090.0       4
1505.0       4
2061.0       4
1805.0       4
1890.0       3
1395.0       3
1704.0       3
1424.0       3
2018.0       3
1459.0       3
531.0        3
1942.0       3
2900.0       3
2690.0       3
2606.0       3
685.0        3
597.0        3
340.0        3
639.0        3
587.0        3
1110.0       3
1446.0       3
710.0        3
1756.0       3
2244.0       3
1230.0       3
2320.0       3
1770.0       3
548.0        3
549.0        3
480.0        3
1848.0       3
1582.0       3
2779.0       3
1325.0       3
2262.0       3
3363.0       3
1298.0       3
1215.0       3
4500.0       3
598.0        3
2575.0       3
1420.0       3
2576.0       3
1762.0       3
1568.0       3
1970.0       3
1730.0       3
2016.0       3
1569.0       3
1880.0       3
1711.0       3
1171.0       3
610.0        3
1410.0       3
1812.0       3
745.0        3
1375.0       3
623.0        3
3100.0       3
2560.0       3
1557.0       3
1940.0       3
930.0        3
2390.0       3
1269.0       3
1202.0       3
1776.0       3
830.0        3
2366.0       3
1789.0       3
1333.0       3
720.0        3
1283.0       3
1368.0       3
523.0        3
1148.0       3
1239.0       3
1383.0       3
734.0        3
5350.0       3
1799.0       3
1956.0       3
1264.0       3
2430.0       3
998.0        3
580.0        3
2325.0       3
1095.0       3
5200.0       3
2134.0       3
1435.0       3
1235.0       3
3880.0       3
3250.0       3
1128.0       3
824.0        3
4739.0       3
1877.0       3
2267.0       3
1444.0       3
1198.0       3
1570.0       3
2086.0       3
585.0        3
1275.0       3
1479.0       3
3950.0       3
1548.0       3
2411.0       3
1492.0       3
1345.0       3
2343.0       3
1023.0       3
626.0        3
690.0        3
2176.0       3
553.0        2
1717.0       2
4337.0       2
1919.0       2
4800.0       2
2835.0       2
2091.0       2
1603.0       2
1067.0       2
1075.0       2
1358.0       2
791.0        2
832.0        2
2295.0       2
594.0        2
3355.0       2
544.0        2
3225.0       2
3360.0       2
1884.0       2
2054.0       2
2965.0       2
949.0        2
2979.0       2
2768.0       2
844.0        2
1010.0       2
362.0        2
2542.0       2
545.0        2
783.0        2
1642.0       2
1271.0       2
2650.0       2
649.0        2
1889.0       2
5201.0       2
2441.0       2
3763.0       2
2289.0       2
1829.0       2
1211.0       2
1314.0       2
1820.0       2
748.0        2
2324.0       2
1280.0       2
2630.0       2
1666.0       2
1304.0       2
560.0        2
2651.0       2
4400.0       2
1777.0       2
1473.0       2
2045.0       2
2070.0       2
2037.0       2
2625.0       2
605.0        2
1596.0       2
392.0        2
3395.0       2
1220.0       2
1845.0       2
2310.0       2
5800.0       2
2895.0       2
493.0        2
1743.0       2
1810.0       2
394.0        2
988.0        2
1290.0       2
625.0        2
1452.0       2
532.0        2
596.0        2
1094.0       2
980.0        2
1581.0       2
2535.0       2
601.0        2
3156.0       2
1617.0       2
3434.0       2
1567.0       2
1361.0       2
1759.0       2
1340.0       2
1540.0       2
2598.0       2
2214.0       2
1645.0       2
2060.0       2
1931.0       2
1560.0       2
3063.0       2
1670.0       2
3025.0       2
458.0        2
1299.0       2
1520.0       2
1733.0       2
2287.0       2
4857.0       2
400.0        2
1224.0       2
1968.0       2
1240.0       2
2185.0       2
2860.0       2
894.0        2
3557.0       2
2033.0       2
2892.0       2
1590.0       2
2786.0       2
1407.0       2
1965.0       2
1986.0       2
2383.0       2
10000.0      2
1802.0       2
524.0        2
965.0        2
958.0        2
1654.0       2
1080.0       2
3844.0       2
4061.0       2
1382.0       2
1104.0       2
997.0        2
6500.0       2
1381.0       2
1758.0       2
1766.0       2
1996.0       2
3731.0       2
1153.0       2
501.0        2
2087.0       2
590.0        2
4848.0       2
1259.0       2
629.0        2
1995.0       2
2850.0       2
526.0        2
3198.0       2
1270.0       2
2273.0       2
2692.0       2
1963.0       2
357.0        2
366.0        2
65517.0      2
926.0        2
1838.0       2
1689.0       2
1369.0       2
1575.0       2
716.0        2
1943.0       2
2356.0       2
2164.0       2
483.0        2
474.0        2
1161.0       2
380.0        2
514.0        2
3185.0       2
547.0        2
539.0        2
1539.0       2
1465.0       2
1338.0       2
2764.0       2
2193.0       2
2872.0       2
1609.0       2
1668.0       2
1255.0       2
730.0        2
465.0        2
1315.0       2
2579.0       2
1816.0       2
468.0        2
1794.0       2
2480.0       2
1352.0       2
1925.0       2
1266.0       2
495.0        2
1414.0       2
1763.0       2
3055.0       2
1484.0       2
780.0        2
1503.0       2
1923.0       2
1740.0       2
867.0        2
970.0        2
1403.0       2
1359.0       2
1775.0       2
2050.0       2
1485.0       2
1151.0       2
1945.0       2
519.0        2
654.0        2
1621.0       1
1219.0       1
2229.0       1
351.0        1
1060.0       1
2781.0       1
3482.0       1
1216.0       1
2425.0       1
2162.0       1
1027.0       1
2851.0       1
3160.0       1
1574.0       1
1944.0       1
3980.0       1
3123.0       1
1622.0       1
2076.0       1
903.0        1
680.0        1
478.0        1
431.0        1
1145.0       1
505.0        1
1285.0       1
1641.0       1
837.0        1
1258.0       1
1297.0       1
621.0        1
1498.0       1
2023.0       1
2066.0       1
4119.0       1
961.0        1
882.0        1
916.0        1
864.0        1
1859.0       1
1764.0       1
2704.0       1
3389.0       1
1738.0       1
1427.0       1
2724.0       1
1460.0       1
3243.0       1
917.0        1
1362.0       1
1955.0       1
1669.0       1
2567.0       1
3173.0       1
1531.0       1
1969.0       1
5133.0       1
1667.0       1
956.0        1
471.0        1
1069.0       1
2085.0       1
1472.0       1
1307.0       1
1791.0       1
6364.0       1
2410.0       1
631.0        1
2109.0       1
1607.0       1
2368.0       1
2354.0       1
1703.0       1
2398.0       1
3900.0       1
3800.0       1
706.0        1
1481.0       1
2750.0       1
2570.0       1
2182.0       1
2012.0       1
2565.0       1
957.0        1
2302.0       1
1999.0       1
946.0        1
826.0        1
1322.0       1
1422.0       1
2168.0       1
2491.0       1
1308.0       1
1431.0       1
2809.0       1
2251.0       1
2711.0       1
4632.0       1
3082.0       1
1938.0       1
2096.0       1
1580.0       1
1974.0       1
655.0        1
2042.0       1
3750.0       1
1854.0       1
1682.0       1
1971.0       1
1926.0       1
2020.0       1
6565.0       1
2271.0       1
4279.0       1
4690.0       1
5513.0       1
1865.0       1
2871.0       1
1252.0       1
1313.0       1
951.0        1
1688.0       1
1655.0       1
1404.0       1
2445.0       1
2475.0       1
3043.0       1
352.0        1
498.0        1
2946.0       1
446.0        1
45283.0      1
4072.0       1
2329.0       1
1928.0       1
1772.0       1
1817.0       1
1993.0       1
2035.0       1
1742.0       1
940.0        1
1165.0       1
2589.0       1
2601.0       1
2051.0       1
520.0        1
810.0        1
1751.0       1
4343.0       1
55000.0      1
620000.0     1
3125.0       1
1676.0       1
1160.0       1
1461.0       1
1746.0       1
1946.0       1
2467.0       1
1527.0       1
2908.0       1
675.0        1
2057.0       1
2090.0       1
1336.0       1
2266.0       1
3390.0       1
2305.0       1
1185.0       1
2452.0       1
2403.0       1
2089.0       1
1961.0       1
1488.0       1
1616.0       1
558.0        1
34426.0      1
1867.0       1
1218.0       1
1274.0       1
49123.0      1
1695.0       1
2753.0       1
2792.0       1
2775.0       1
2195.0       1
1707.0       1
1611.0       1
1558.0       1
1177.0       1
2597.0       1
2864.0       1
1914.0       1
2280.0       1
1837.0       1
2145.0       1
642857.0     1
581.0        1
711.0        1
324.0        1
1562.0       1
652.0        1
4328.0       1
804.0        1
2072.0       1
2276.0       1
3350.0       1
1721.0       1
853.0        1
842.0        1
3556.0       1
1678.0       1
1646.0       1
2464.0       1
1445.0       1
2143.0       1
2395.0       1
2747.0       1
1174.0       1
3375.0       1
2492.0       1
1702.0       1
1559.0       1
1785.0       1
3192.0       1
1139.0       1
2077.0       1
1228.0       1
1941.0       1
2256.0       1
1921.0       1
921.0        1
1169.0       1
1706.0       1
1685.0       1
633.0        1
6926.0       1
536.0        1
2495.0       1
3829.0       1
1337.0       1
4115.0       1
3194.0       1
2165.0       1
6240.0       1
11000.0      1
3850.0       1
9001.0       1
2987.0       1
302.0        1
2360.0       1
1752.0       1
872.0        1
4553.0       1
2079.0       1
2189.0       1
3130.0       1
4889.0       1
1417.0       1
1638.0       1
1608.0       1
1922.0       1
1983.0       1
1428.0       1
1006.0       1
1458.0       1
2252.0       1
3343.0       1
4550.0       1
3059.0       1
1020.0       1
642.0        1
1836.0       1
767.0        1
2013.0       1
1918.0       1
1809.0       1
2108.0       1
809.0        1
2436.0       1
4891.0       1
2503.0       1
1696.0       1
2470.0       1
969.0        1
3410.0       1
1966.0       1
1747.0       1
2662.0       1
1127.0       1
1833.0       1
1496.0       1
1059.0       1
3154.0       1
1545.0       1
1844.0       1
2338.0       1
2201.0       1
1749.0       1
1173.0       1
1034.0       1
1632.0       1
1830.0       1
2285.0       1
722.0        1
1584.0       1
337.0        1
683.0        1
3020.0       1
1455.0       1
1118.0       1
884.0        1
2177.0       1
743.0        1
985.0        1
4246.0       1
58228.0      1
2159.0       1
2554.0       1
1330.0       1
1591.0       1
4613.0       1
1494.0       1
2862.0       1
1774.0       1
1167.0       1
1610.0       1
1554.0       1
535.0        1
820.0        1
2341.0       1
2754.0       1
1478.0       1
1154.0       1
2278.0       1
1991.0       1
250.0        1
2043.0       1
2153.0       1
2557.0       1
4300.0       1
2034.0       1
996.0        1
1477.0       1
2344.0       1
2943.0       1
570.0        1
1449.0       1
2693.0       1
662.0        1
566667.0     1
2133.0       1
6123.0       1
1672.0       1
2069.0       1
1631.0       1
1517.0       1
2801.0       1
3270.0       1
1296.0       1
410.0        1
1049.0       1
693.0        1
670.0        1
1184.0       1
562.0        1
1786.0       1
3215.0       1
681.0        1
525.0        1
893.0        1
462.0        1
3462.0       1
835.0        1
3958.0       1
726.0        1
1665.0       1
2705.0       1
2919.0       1
2903.0       1
2698.0       1
1351.0       1
2428.0       1
1507.0       1
2380.0       1
2635.0       1
963.0        1
1099.0       1
1286.0       1
1411.0       1
1091.0       1
2055.0       1
1587.0       1
1784.0       1
885.0        1
2675.0       1
72.0         1
1967.0       1
773.0        1
845.0        1
1267.0       1
1653.0       1
1897.0       1
1443.0       1
460.0        1
1913.0       1
3344.0       1
2527.0       1
2080.0       1
1349.0       1
1416.0       1
2510.0       1
1917.0       1
2537.0       1
1125.0       1
7603.0       1
417.0        1
1257.0       1
904.0        1
2297.0       1
2111.0       1
4250.0       1
744.0        1
1205.0       1
870.0        1
1406.0       1
2538.0       1
2112.0       1
1140.0       1
6700.0       1
1869.0       1
1057.0       1
2315.0       1
2144.0       1
1234.0       1
695.0        1
2645.0       1
333.0        1
405.0        1
2609.0       1
1471.0       1
476.0        1
699.0        1
2113.0       1
1639.0       1
637.0        1
2152.0       1
1902.0       1
898.0        1
696.0        1
661.0        1
339.0        1
658.0        1
516.0        1
2937.0       1
1107.0       1
1489.0       1
2038.0       1
1194.0       1
555.0        1
2030.0       1
412.0        1
636.0        1
1030.0       1
568.0        1
318.0        1
2385.0       1
1343.0       1
875000.0     1
995.0        1
669.0        1
18129.0      1
3806.0       1
3764.0       1
1251.0       1
3008.0       1
1614.0       1
1470.0       1
755.0        1
760.0        1
3216.0       1
1495.0       1
1628.0       1
2715.0       1
770.0        1
763.0        1
2655.0       1
1662.0       1
1556.0       1
3040.0       1
1736.0       1
2808.0       1
2995.0       1
1635.0       1
1408.0       1
1779.0       1
1376.0       1
2265.0       1
1056.0       1
2572.0       1
2780.0       1
3112.0       1
2318.0       1
4095.0       1
2525.0       1
3830.0       1
1475.0       1
2404.0       1
1636.0       1
2405.0       1
1715.0       1
1124.0       1
2019.0       1
3142.0       1
2129.0       1
1853.0       1
741.0        1
1792.0       1
1826.0       1
2208.0       1
891.0        1
1724.0       1
1510.0       1
1519.0       1
2940.0       1
1551.0       1
484.0        1
1158.0       1
1835.0       1
2997.0       1
4640.0       1
3305.0       1
1126.0       1
2097.0       1
1615.0       1
3601.0       1
2104.0       1
2235.0       1
2783.0       1
823.0        1
488.0        1
1441.0       1
546.0        1
671.0        1
2580.0       1
1734.0       1
2813.0       1
2333.0       1
1915.0       1
1378.0       1
684.0        1
1076.0       1
687.0        1
2286.0       1
790.0        1
1623.0       1
1159.0       1
574.0        1
2291.0       1
1233.0       1
12645.0      1
1133.0       1
624.0        1
1353.0       1
1329.0       1
728.0        1
2117.0       1
1244.0       1
396.0        1
497.0        1
634.0        1
1987.0       1
2059.0       1
2359.0       1
2670.0       1
2321.0       1
300.0        1
983.0        1
Name: count, dtype: int64

In [75]:
# df.insert(loc=1,column='property_type',value='flat')

In [76]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   society          2996 non-null   object
 2   price            2995 non-null   float64
 3   price_per_sqft   2995 non-null   float64
 4   area             2995 non-null   float64
 5   areaWithType     2996 non-null   object
 6   bedRoom          2996 non-null   int64
 7   bathroom         2996 non-null   int64
 8   balcony          2996 non-null   object
 9   additionalRoom   2996 non-null   object
 10  address          2990 non-null   object
 11  floorNum         2996 non-null   object
 12  facing           2996 non-null   object
 13  agePossession    2995 non-null   object
 14  nearbyLocations  2906 non-null   object
 15  description      2996 non-null   object
 16  furnishDetails   2199 non-null   object
 17  features         2590 non-null   object
 18  rating           2667 non-null   object
dtypes: float64(3), int64(2), object(14)
memory usage: 468.1+ KB

In [78]:
df.shape

(2996, 19)

In [79]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [80]:
# extracting sector information from property_name column and adding a sector column
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [81]:
df['sector'] = df['sector'].str.lower()

In [82]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,krishna colony,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,ashok vihar,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,sohna,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,sector 61,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,sector 92,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [83]:
df['sector'].value_counts()

sector
sohna                            159
sector 102                       113
sector 85                        110
sector 92                        100
sector 69                         92
sector 90                         90
sector 65                         89
sector 81                         87
sector 79                         80
sector 83                         68
sector 104                        65
sector 37d                        65
sector 86                         63
sector 107                        60
sector 95                         57
sector 108                        55
sector 89                         54
sector 70                         53
sector 37c                        53
sector 109                        52
sector 84                         51
sector-33 sohna                   49
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                        41
sector 70a                        40
sector 106                        37
sector 99a                        32
sector 82                         32
sector 68                         30
sector 49                         30
sector 77                         29
sector 66                         29
palam vihar                       28
sector 48                         28
sector 71                         27
sector 72                         25
sector 88a                        23
nirvana country                   22
sector 112                        21
sector 111                        21
sector 67a                        21
sector 54                         20
sector 82a                        19
sector 22                         18
sector 74                         18
sector 78                         18
sector 62                         17
sector 99                         16
sector 63a                        16
sector 91                         15
sector 110                        15
sector 60                         14
sector 1 imt manesar              14
gwal pahari                       14
dlf phase 5                       13
sector 63                         13
sector 36a                        13
dlf phase 4                       13
sector 76                         12
sector 53                         12
sector 93                         11
sector 52                         11
sector 9a                         10
sector 1a imt manesar             10
sector 33                          9
sector 95a                         9
sector 59                          8
sector 89 a                        8
sector 47                          8
sector 3                           7
mehrauli  road                     7
sector 43                          7
dwarka expressway                  7
sector 58                          7
laxman vihar                       6
sector 51                          6
sector 36 sohna                    6
chakkarpur                         5
sector 80                          5
sector 2                           5
sector 10a                         5
sector 30                          5
sector 39                          5
sector 50                          5
ashok vihar phase 2                5
sushant lok phase 1                5
dlf phase 2                        4
sector 1                           4
valley view estate                 4
adarsh nagar                       4
dlf phase 3                        4
new                                4
sohna road                         3
dayanand colony                    3
ashok vihar                        3
sector 88b                         3
manesar                            3
sector 55                          3
sector 31                          3
imt manesar                        3
sector 36                          3
new palam vihar                    3
sector 28                          3
sector 12                          3
mg road                            3
sector 110 a                       3
ashok vihar phase 3 extension      2
krishna colony                     2
sector 57                          2
block a surya vihar                2
sector 32                          2
sushant lok phase 3                2
sector 45                          2
iffco chowk                        2
sector 4                           2
malibu town                        2
sector 7                           2
sector 73                          2
sushant lok                        2
sector 21                          2
shanti nagar                       2
surat nagar 1                      2
shankar vihar                      2
sector 24                          2
dharam colony                      2
sector 105                         2
golf course ext road               2
samaspur                           2
sector-11 sohna                    2
suncity                            2
ambience island                    2
sector 15                          2
sector 14                          2
sector 11                          2
sector 23a                         2
sector-2 sohna                     2
sispal vihar                       2
sector-7 hous                      1
sector 15 part 1                   1
sector 38                          1
heritage city                      1
sector 41                          1
bhawani enclave                    1
rajiv colony                       1
kanahi                             1
sector 12a                         1
garauli kalan                      1
near sector 1 market               1
golf course road                   1
lajpat nagar                       1
carterpuri village                 1
sector 37a                         1
ats marigold                       1
surya vihar                        1
near pataudi chowk                 1
cyber city                         1
new colony                         1
subhash nagar                      1
sultanpur                          1
civil l                            1
new colony, sector 7               1
sai kunj                           1
old delhi road, opp sector-14      1
sector 5 chowk                     1
faridabad road                     1
sector-5 sohna                     1
patel nagar                        1
nirvana country pocket h           1
sector 5                           1
laxman vihar phase 2               1
bhondsi                            1
palam vihar extension              1
new palam vihar phase 2            1
sector-35 sohna                    1
sector 4 urban estate              1
saroop garden rajendra park        1
south city 1                       1
bptp                               1
sector 9                           1
sector 40                          1
rajendra park                      1
godrej aria , sector 79 ,          1
Name: count, dtype: int64

In [84]:
df['sector'].isnull().sum()

np.int64(0)

In [85]:
# replacing by actual sector
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [86]:
df['sector'].value_counts()

sector
sohna road                       159
sector 102                       113
sector 85                        110
sector 92                        100
sector 69                         92
sector 90                         90
sector 65                         89
sector 81                         87
sector 79                         80
sector 83                         68
sector 104                        67
sector 95                         66
sector 37d                        65
sector 86                         63
sector 89                         62
sector 107                        60
sector 33                         58
sector 108                        55
sector 37c                        53
sector 70                         53
sector 109                        52
sector 84                         51
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                        41
sector 70a                        40
sector 106                        37
sector 2                          34
sector 99a                        32
sector 82                         32
manesar                           30
sector 49                         30
sector 68                         30
sector 77                         29
sector 66                         29
sector 48                         28
sector 71                         27
sector 50                         27
sector 72                         25
sector 43                         25
sector 28                         24
sector 88a                        23
sector 54                         22
sector 111                        21
sector 112                        21
sector 67a                        21
sector 82a                        19
sector 110                        18
gwal pahari                       18
sector 78                         18
sector 74                         18
sector 22                         18
sector 62                         17
sector 99                         16
sector 63a                        16
sector 91                         15
sector 60                         14
sector 63                         13
sector 36a                        13
sector 53                         12
sector 76                         12
sector 12                         11
sector 52                         11
sector 93                         11
sector 3                          10
sector 9a                         10
sector 47                         10
sector 4                           9
sector 14                          9
sector 36                          9
sector 59                          8
sector 58                          7
dwarka expressway                  7
sector 51                          6
sector 24                          6
sector 7                           5
sector 3 phase 2                   5
sector 39                          5
sector 30                          5
sector 80                          5
sector 10a                         5
sector 1                           4
sector 57                          4
new                                4
sector 25                          4
sector 88b                         3
sector 6                           3
sector 21                          3
sector 15                          3
sector 31                          3
sector 105                         3
new sector 2                       3
sector 11                          3
sector 55                          3
sohna road road                    3
block a sector 21                  2
sector 73                          2
sector 41                          2
samaspur                           2
golf course ext road               2
sispal vihar                       2
shankar vihar                      2
shanti nagar                       2
ambience island                    2
sector 23                          2
iffco chowk                        2
sector 3 phase 3 extension         2
sector 32                          2
sushant lok                        2
sector-2 sohna road                2
sector-11 sohna road               2
sector 45                          2
sector-7 hous                      1
sector 15 part 1                   1
near sector 1 market               1
golf course road                   1
garauli kalan                      1
bhawani enclave                    1
rajiv colony                       1
kanahi                             1
sector 38                          1
heritage city                      1
lajpat nagar                       1
sector 7, sector 7                 1
sultanpur                          1
civil l                            1
sai kunj                           1
cyber city                         1
ats marigold                       1
near pataudi chowk                 1
old delhi road, opp sector-14      1
sector 5 chowk                     1
faridabad road                     1
sector-5 sohna road                1
sector 37a                         1
carterpuri village                 1
sector 50 pocket h                 1
sector 5                           1
new sector 2 phase 2               1
sector-35 sohna road               1
sector 4 urban estate              1
saroop garden sector 105           1
bptp                               1
sector 9                           1
sector 40                          1
godrej aria , sector 79 ,          1
Name: count, dtype: int64

In [87]:
df[df['sector'] == 'new']

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2048,4 BHK Flat in New Gurgaon,dlf 76,4.00,new,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4,NA,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2811,2 BHK Flat in New Gurgaon,takshila heights sector 37 c,0.67,new,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3,NA,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2907,2 BHK Flat in New Gurgaon,green court,0.38,new,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7,NA,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2980,4 BHK Flat in New Gurgaon,sare homes,0.85,new,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3,NA,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [88]:
df.loc[2811,'sector'] = 'sector 37'
df.loc[2980,'sector'] = 'sector 92'
df.loc[2907,'sector'] = 'sector 90'
df.loc[2048,'sector'] = 'sector 76'

In [89]:
df[df['sector'] == 'new sector 2']

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
31,2 BHK Flat in New Palam Vihar,ompee k s residency,1.60,new sector 2,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1,NA,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
89,2 BHK Flat in New Palam Vihar,my home,0.28,new sector 2,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2,NA,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2854,2 BHK Flat in New Palam Vihar,my home,0.22,new sector 2,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1,NA,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [90]:
df.loc[[89,31,2854],'sector'] = 'sector 110'

In [91]:
df['sector'].value_counts()

sector
sohna road                       159
sector 102                       113
sector 85                        110
sector 92                        101
sector 69                         92
sector 90                         91
sector 65                         89
sector 81                         87
sector 79                         80
sector 83                         68
sector 104                        67
sector 95                         66
sector 37d                        65
sector 86                         63
sector 89                         62
sector 107                        60
sector 33                         58
sector 108                        55
sector 70                         53
sector 37c                        53
sector 109                        52
sector 84                         51
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                        41
sector 70a                        40
sector 106                        37
sector 2                          34
sector 99a                        32
sector 82                         32
manesar                           30
sector 49                         30
sector 68                         30
sector 77                         29
sector 66                         29
sector 48                         28
sector 71                         27
sector 50                         27
sector 43                         25
sector 72                         25
sector 28                         24
sector 88a                        23
sector 54                         22
sector 111                        21
sector 110                        21
sector 112                        21
sector 67a                        21
sector 82a                        19
sector 78                         18
gwal pahari                       18
sector 74                         18
sector 22                         18
sector 62                         17
sector 63a                        16
sector 99                         16
sector 91                         15
sector 60                         14
sector 63                         13
sector 36a                        13
sector 76                         13
sector 53                         12
sector 12                         11
sector 93                         11
sector 52                         11
sector 3                          10
sector 9a                         10
sector 47                         10
sector 4                           9
sector 36                          9
sector 14                          9
sector 59                          8
dwarka expressway                  7
sector 58                          7
sector 51                          6
sector 24                          6
sector 80                          5
sector 7                           5
sector 10a                         5
sector 3 phase 2                   5
sector 39                          5
sector 30                          5
sector 1                           4
sector 57                          4
sector 25                          4
sector 88b                         3
sector 6                           3
sector 31                          3
sector 15                          3
sector 55                          3
sohna road road                    3
sector 105                         3
sector 21                          3
sector 11                          3
iffco chowk                        2
sector 3 phase 3 extension         2
block a sector 21                  2
sector 73                          2
samaspur                           2
sispal vihar                       2
golf course ext road               2
shankar vihar                      2
sector-11 sohna road               2
ambience island                    2
sector 23                          2
sector 41                          2
sector-2 sohna road                2
sector 32                          2
shanti nagar                       2
sushant lok                        2
sector 45                          2
sector 15 part 1                   1
sector-7 hous                      1
rajiv colony                       1
near sector 1 market               1
golf course road                   1
bhawani enclave                    1
garauli kalan                      1
sai kunj                           1
kanahi                             1
sector 38                          1
heritage city                      1
lajpat nagar                       1
sector 7, sector 7                 1
sultanpur                          1
civil l                            1
sector 37a                         1
ats marigold                       1
near pataudi chowk                 1
cyber city                         1
sector 5                           1
old delhi road, opp sector-14      1
sector 5 chowk                     1
faridabad road                     1
sector-5 sohna road                1
carterpuri village                 1
new sector 2 phase 2               1
sector 50 pocket h                 1
sector-35 sohna road               1
sector 37                          1
sector 4 urban estate              1
saroop garden sector 105           1
bptp                               1
sector 9                           1
sector 40                          1
godrej aria , sector 79 ,          1
Name: count, dtype: int64

In [92]:
df.duplicated().sum()

np.int64(0)

In [93]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,sector 7,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,sector 3,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,sohna road,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,sector 61,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,sector 92,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [94]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [95]:
df.duplicated().sum()

np.int64(124)

In [96]:
df.shape

(2996, 16)

In [97]:
df.drop_duplicates(keep='first', inplace=True)

In [98]:
df.shape

(2872, 16)

In [99]:
df.to_csv('../data/flats_cleaned.csv',index=False)